/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Returned when the request cannot be processed due to authentication or authorization issues
 */
export type ForbiddenErrorResponseData = {
  /**
   * Error message for forbidden access
   */
  detail?: string;
};

/**
 * Returned when the request cannot be processed due to authentication or authorization issues
 */
export class ForbiddenErrorResponse extends Error {
  /**
   * Error message for forbidden access
   */
  detail?: string;

  /** The original data that was passed to this error instance. */
  data$: ForbiddenErrorResponseData;

  constructor(err: ForbiddenErrorResponseData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.detail != null) this.detail = err.detail;

    this.name = "ForbiddenErrorResponse";
  }
}

/** @internal */
export const ForbiddenErrorResponse$inboundSchema: z.ZodType<
  ForbiddenErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  detail: z.string().default("Access forbidden"),
})
  .transform((v) => {
    return new ForbiddenErrorResponse(v);
  });

/** @internal */
export type ForbiddenErrorResponse$Outbound = {
  detail?: string;
};

/** @internal */
export const ForbiddenErrorResponse$outboundSchema: z.ZodType<
  ForbiddenErrorResponse$Outbound,
  z.ZodTypeDef,
  ForbiddenErrorResponse
> = z.instanceof(ForbiddenErrorResponse)
  .transform(v => v.data$)
  .pipe(z.object({
    detail: z.string().default("Access forbidden"),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ForbiddenErrorResponse$ {
  /** @deprecated use `ForbiddenErrorResponse$inboundSchema` instead. */
  export const inboundSchema = ForbiddenErrorResponse$inboundSchema;
  /** @deprecated use `ForbiddenErrorResponse$outboundSchema` instead. */
  export const outboundSchema = ForbiddenErrorResponse$outboundSchema;
  /** @deprecated use `ForbiddenErrorResponse$Outbound` instead. */
  export type Outbound = ForbiddenErrorResponse$Outbound;
}
