/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type InteractModelsErrorResponseData = {
  /**
   * Error message describing what went wrong
   */
  detail: string;
};

export class InteractModelsErrorResponse extends Error {
  /**
   * Error message describing what went wrong
   */
  detail: string;

  /** The original data that was passed to this error instance. */
  data$: InteractModelsErrorResponseData;

  constructor(err: InteractModelsErrorResponseData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.detail = err.detail;

    this.name = "InteractModelsErrorResponse";
  }
}

/** @internal */
export const InteractModelsErrorResponse$inboundSchema: z.ZodType<
  InteractModelsErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  detail: z.string(),
})
  .transform((v) => {
    return new InteractModelsErrorResponse(v);
  });

/** @internal */
export type InteractModelsErrorResponse$Outbound = {
  detail: string;
};

/** @internal */
export const InteractModelsErrorResponse$outboundSchema: z.ZodType<
  InteractModelsErrorResponse$Outbound,
  z.ZodTypeDef,
  InteractModelsErrorResponse
> = z.instanceof(InteractModelsErrorResponse)
  .transform(v => v.data$)
  .pipe(z.object({
    detail: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InteractModelsErrorResponse$ {
  /** @deprecated use `InteractModelsErrorResponse$inboundSchema` instead. */
  export const inboundSchema = InteractModelsErrorResponse$inboundSchema;
  /** @deprecated use `InteractModelsErrorResponse$outboundSchema` instead. */
  export const outboundSchema = InteractModelsErrorResponse$outboundSchema;
  /** @deprecated use `InteractModelsErrorResponse$Outbound` instead. */
  export type Outbound = InteractModelsErrorResponse$Outbound;
}
