/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ServerErrorResponseData = {
  /**
   * Detailed error message from the server
   */
  detail: string;
};

export class ServerErrorResponse extends Error {
  /**
   * Detailed error message from the server
   */
  detail: string;

  /** The original data that was passed to this error instance. */
  data$: ServerErrorResponseData;

  constructor(err: ServerErrorResponseData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.detail = err.detail;

    this.name = "ServerErrorResponse";
  }
}

/** @internal */
export const ServerErrorResponse$inboundSchema: z.ZodType<
  ServerErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  detail: z.string(),
})
  .transform((v) => {
    return new ServerErrorResponse(v);
  });

/** @internal */
export type ServerErrorResponse$Outbound = {
  detail: string;
};

/** @internal */
export const ServerErrorResponse$outboundSchema: z.ZodType<
  ServerErrorResponse$Outbound,
  z.ZodTypeDef,
  ServerErrorResponse
> = z.instanceof(ServerErrorResponse)
  .transform(v => v.data$)
  .pipe(z.object({
    detail: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ServerErrorResponse$ {
  /** @deprecated use `ServerErrorResponse$inboundSchema` instead. */
  export const inboundSchema = ServerErrorResponse$inboundSchema;
  /** @deprecated use `ServerErrorResponse$outboundSchema` instead. */
  export const outboundSchema = ServerErrorResponse$outboundSchema;
  /** @deprecated use `ServerErrorResponse$Outbound` instead. */
  export type Outbound = ServerErrorResponse$Outbound;
}
