/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Standard error response containing details about the error
 */
export type WindowsModelsErrorResponseData = {
  /**
   * Error message describing what went wrong
   */
  detail: string;
};

/**
 * Standard error response containing details about the error
 */
export class WindowsModelsErrorResponse extends Error {
  /**
   * Error message describing what went wrong
   */
  detail: string;

  /** The original data that was passed to this error instance. */
  data$: WindowsModelsErrorResponseData;

  constructor(err: WindowsModelsErrorResponseData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.detail = err.detail;

    this.name = "WindowsModelsErrorResponse";
  }
}

/** @internal */
export const WindowsModelsErrorResponse$inboundSchema: z.ZodType<
  WindowsModelsErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  detail: z.string(),
})
  .transform((v) => {
    return new WindowsModelsErrorResponse(v);
  });

/** @internal */
export type WindowsModelsErrorResponse$Outbound = {
  detail: string;
};

/** @internal */
export const WindowsModelsErrorResponse$outboundSchema: z.ZodType<
  WindowsModelsErrorResponse$Outbound,
  z.ZodTypeDef,
  WindowsModelsErrorResponse
> = z.instanceof(WindowsModelsErrorResponse)
  .transform(v => v.data$)
  .pipe(z.object({
    detail: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WindowsModelsErrorResponse$ {
  /** @deprecated use `WindowsModelsErrorResponse$inboundSchema` instead. */
  export const inboundSchema = WindowsModelsErrorResponse$inboundSchema;
  /** @deprecated use `WindowsModelsErrorResponse$outboundSchema` instead. */
  export const outboundSchema = WindowsModelsErrorResponse$outboundSchema;
  /** @deprecated use `WindowsModelsErrorResponse$Outbound` instead. */
  export type Outbound = WindowsModelsErrorResponse$Outbound;
}
