/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { agentRun } from "../../funcs/agentRun.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  instanceId: z.string(),
  claudeRequest: components.ClaudeRequest$inboundSchema,
};

export const tool$agentRun: ToolDefinition<typeof args> = {
  name: "agent-run",
  description: `Run Agent

Run a loop with Anthropic's computer use agent to perform tasks on the VM.

Requires API key authentication.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await agentRun(
      client,
      args.instanceId,
      args.claudeRequest,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
