/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { agentAnswer } from "../../funcs/agentAnswer.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  agentId: z.string(),
  requestBody: operations.AnswerResponse$inboundSchema,
};

export const tool$agentAnswer: ToolDefinition<typeof args> = {
  name: "agent-answer",
  description: `Respond To Agent

Send a human response to a waiting agent and resume its execution.

Requires API key authentication.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await agentAnswer(
      client,
      args.agentId,
      args.requestBody,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
