/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { filesUpload } from "../../funcs/filesUpload.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  instanceId: z.string(),
  s3VMUploadRequest: components.S3VMUploadRequest$inboundSchema,
};

export const tool$filesUpload: ToolDefinition<typeof args> = {
  name: "files-upload",
  description: `Upload To Vm

Upload a file from S3 to the VM

Takes an S3 URL (often from FileUploader component) and transfers it to the VM.
Updates the files.uploads array in the vm_instances table to track the file.

Requires API key authentication.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await filesUpload(
      client,
      args.instanceId,
      args.s3VMUploadRequest,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
