/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { filesDownload } from "../../funcs/filesDownload.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  instanceId: z.string(),
  requestBody: z.record(z.string()),
};

export const tool$filesDownload: ToolDefinition<typeof args> = {
  name: "files-download",
  description: `Get File

Get a secure download link for a file on the instance

Generates a presigned S3 URL for the client to download the file directly

Requires API key authentication.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await filesDownload(
      client,
      args.instanceId,
      args.requestBody,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
