/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { interactKeypress } from "../../funcs/interactKeypress.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  instanceId: z.string(),
  keyRequest: components.KeyRequest$inboundSchema,
};

export const tool$interactKeypress: ToolDefinition<typeof args> = {
  name: "interact-keypress",
  description: `Keypress

Press the specified keys simultaneously (e.g. ['ctrl', 'alt', 'delete'])

Requires API key authentication.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await interactKeypress(
      client,
      args.instanceId,
      args.keyRequest,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
