/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { interactScroll } from "../../funcs/interactScroll.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ScrollRequest$inboundSchema,
};

export const tool$interactScroll: ToolDefinition<typeof args> = {
  name: "interact-scroll",
  description: `Scroll

Scroll at the specified coordinates

Requires API key authentication.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await interactScroll(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
