/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { interactClick } from "../../funcs/interactClick.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ClickRequest$inboundSchema,
};

export const tool$interactClick: ToolDefinition<typeof args> = {
  name: "interact-click",
  description: `Click

Perform a click operation at the specified coordinates or current position

- If x and y are provided, click at those coordinates
- If x and y are omitted, click at the current cursor position
- Use button="left", clicks=1 for a single left click
- Use button="right", clicks=1 for a right click
- Use button="middle", clicks=1 for a middle click
- Use button="left", clicks=2 for a double click

Requires API key authentication.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await interactClick(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
