/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { interactMove } from "../../funcs/interactMove.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  instanceId: z.string(),
  mouseMoveRequest: components.MouseMoveRequest$inboundSchema,
};

export const tool$interactMove: ToolDefinition<typeof args> = {
  name: "interact-move",
  description: `Move Mouse

Move the mouse to the specified coordinates

Requires API key authentication.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await interactMove(
      client,
      args.instanceId,
      args.mouseMoveRequest,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
