/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { interactDrag } from "../../funcs/interactDrag.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  instanceId: z.string(),
  dragRequest: components.DragRequest$inboundSchema,
};

export const tool$interactDrag: ToolDefinition<typeof args> = {
  name: "interact-drag",
  description: `Drag

Perform a drag operation along a path of coordinates

- path: List of points to drag through, each with 'x' and 'y' coordinates
- button: Mouse button to use for dragging (default: "left")

Requires API key authentication.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await interactDrag(
      client,
      args.instanceId,
      args.dragRequest,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
