/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { interactInstall } from "../../funcs/interactInstall.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.InstallRequest$inboundSchema,
};

export const tool$interactInstall: ToolDefinition<typeof args> = {
  name: "interact-install",
  description: `Install Applications

Install Chocolatey packages on a Windows instance. Find a list of packages here: https://community.chocolatey.org/packages.

Requires API key authentication.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await interactInstall(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
