/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { windowsTerminate } from "../../funcs/windowsTerminate.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  instanceId: z.string(),
};

export const tool$windowsTerminate: ToolDefinition<typeof args> = {
  name: "windows-terminate",
  description: `Terminate Instance

Requires API key authentication.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await windowsTerminate(
      client,
      args.instanceId,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
