/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { windowsInstances } from "../../funcs/windowsInstances.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$windowsInstances: ToolDefinition = {
  name: "windows-instances",
  description: `Get Instances

Requires API key authentication.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await windowsInstances(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
