/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { windowsStart } from "../../funcs/windowsStart.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.InstanceRequest$inboundSchema,
};

export const tool$windowsStart: ToolDefinition<typeof args> = {
  name: "windows-start",
  description: `Start Instance

Start a new Windows  instance.

- timeout_minutes: Optional timeout in minutes (default: 60)

Requires API key authentication.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await windowsStart(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
