/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SkylightCore } from "../core.js";
import { encodeJSON, encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import * as components from "../models/components/index.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Upload To Vm
 *
 * @remarks
 * Upload a file from S3 to the VM
 *
 * Takes an S3 URL (often from FileUploader component) and transfers it to the VM.
 * Updates the files.uploads array in the vm_instances table to track the file.
 *
 * Requires API key authentication.
 */
export function filesUpload(
  client: SkylightCore,
  instanceId: string,
  s3VMUploadRequest: components.S3VMUploadRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    components.FileUploadResponse,
    | errors.InteractModelsErrorResponse
    | errors.ForbiddenErrorResponse
    | errors.HTTPValidationError
    | errors.InteractModelsErrorResponse
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client,
    instanceId,
    s3VMUploadRequest,
    options,
  ));
}

async function $do(
  client: SkylightCore,
  instanceId: string,
  s3VMUploadRequest: components.S3VMUploadRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      components.FileUploadResponse,
      | errors.InteractModelsErrorResponse
      | errors.ForbiddenErrorResponse
      | errors.HTTPValidationError
      | errors.InteractModelsErrorResponse
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const input: operations.UploadRequest = {
    instanceId: instanceId,
    s3VMUploadRequest: s3VMUploadRequest,
  };

  const parsed = safeParse(
    input,
    (value) => operations.UploadRequest$outboundSchema.parse(value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = encodeJSON("body", payload.S3VMUploadRequest, { explode: true });

  const pathParams = {
    instance_id: encodeSimple("instance_id", payload.instance_id, {
      explode: false,
      charEncoding: "percent",
    }),
  };

  const path = pathToFunc("/windows/files/upload/{instance_id}")(pathParams);

  const headers = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "application/json",
  }));

  const secConfig = await extractSecurity(client._options.apikey);
  const securityInput = secConfig == null ? {} : { apikey: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "upload",
    oAuth2Scopes: [],

    resolvedSecurity: requestSecurity,

    securitySource: client._options.apikey,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    body: body,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: ["400", "403", "422", "4XX", "500", "5XX"],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    components.FileUploadResponse,
    | errors.InteractModelsErrorResponse
    | errors.ForbiddenErrorResponse
    | errors.HTTPValidationError
    | errors.InteractModelsErrorResponse
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.json(200, components.FileUploadResponse$inboundSchema),
    M.jsonErr(400, errors.InteractModelsErrorResponse$inboundSchema),
    M.jsonErr(403, errors.ForbiddenErrorResponse$inboundSchema),
    M.jsonErr(422, errors.HTTPValidationError$inboundSchema),
    M.jsonErr(500, errors.InteractModelsErrorResponse$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
