/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { SkylightCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope, mcpScopes } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$agentRun } from "./tools/agentRun.js";
import { tool$agentStatus } from "./tools/agentStatus.js";
import { tool$agentStop } from "./tools/agentStop.js";
import { tool$interactClick } from "./tools/interactClick.js";
import { tool$interactDrag } from "./tools/interactDrag.js";
import { tool$interactGetFile } from "./tools/interactGetFile.js";
import { tool$interactInstall } from "./tools/interactInstall.js";
import { tool$interactKeypress } from "./tools/interactKeypress.js";
import { tool$interactMove } from "./tools/interactMove.js";
import { tool$interactScreenshot } from "./tools/interactScreenshot.js";
import { tool$interactScroll } from "./tools/interactScroll.js";
import { tool$interactType } from "./tools/interactType.js";
import { tool$windowsInstances } from "./tools/windowsInstances.js";
import { tool$windowsPause } from "./tools/windowsPause.js";
import { tool$windowsResume } from "./tools/windowsResume.js";
import { tool$windowsStart } from "./tools/windowsStart.js";
import { tool$windowsState } from "./tools/windowsState.js";
import { tool$windowsTerminate } from "./tools/windowsTerminate.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  apikey?: SDKOptions["apikey"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "Skylight",
    version: "0.0.1",
  });

  const client = new SkylightCore({
    apikey: deps.apikey,
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
  });

  const scopes = new Set(deps.scopes ?? mcpScopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, client, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$windowsStart);
  tool(tool$windowsPause);
  tool(tool$windowsResume);
  tool(tool$windowsState);
  tool(tool$windowsInstances);
  tool(tool$windowsTerminate);
  tool(tool$interactInstall);
  tool(tool$interactClick);
  tool(tool$interactDrag);
  tool(tool$interactScreenshot);
  tool(tool$interactMove);
  tool(tool$interactKeypress);
  tool(tool$interactType);
  tool(tool$interactScroll);
  tool(tool$interactGetFile);
  tool(tool$agentRun);
  tool(tool$agentStop);
  tool(tool$agentStatus);

  return server;
}
