/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentAnswer } from "../funcs/agentAnswer.js";
import { agentRun } from "../funcs/agentRun.js";
import { agentStatus } from "../funcs/agentStatus.js";
import { agentStop } from "../funcs/agentStop.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Agent extends ClientSDK {
  /**
   * Run Agent
   *
   * @remarks
   * Run a loop with Anthropic's computer use agent to perform tasks on the VM.
   *
   * Requires API key authentication.
   */
  async run(
    instanceId: string,
    claudeRequest: components.ClaudeRequest,
    options?: RequestOptions,
  ): Promise<components.StandardResponse> {
    return unwrapAsync(agentRun(
      this,
      instanceId,
      claudeRequest,
      options,
    ));
  }

  /**
   * Stop Agent
   *
   * @remarks
   * Stop a running agent for a specific instance.
   *
   * Requires API key authentication.
   */
  async stop(
    instanceId: string,
    options?: RequestOptions,
  ): Promise<components.StandardResponse> {
    return unwrapAsync(agentStop(
      this,
      instanceId,
      options,
    ));
  }

  /**
   * Respond To Agent
   *
   * @remarks
   * Send a human response to a waiting agent and resume its execution.
   *
   * Requires API key authentication.
   */
  async answer(
    agentId: string,
    requestBody: operations.AnswerResponse,
    options?: RequestOptions,
  ): Promise<components.StandardResponse> {
    return unwrapAsync(agentAnswer(
      this,
      agentId,
      requestBody,
      options,
    ));
  }

  /**
   * Get Agent State
   *
   * @remarks
   * Get the current status of an agent for a specific instance.
   *
   * Requires API key authentication.
   */
  async status(
    agentId: string,
    options?: RequestOptions,
  ): Promise<components.AgentStatusResponse> {
    return unwrapAsync(agentStatus(
      this,
      agentId,
      options,
    ));
  }
}
