/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentRun } from "../funcs/agentRun.js";
import { agentStatus } from "../funcs/agentStatus.js";
import { agentStop } from "../funcs/agentStop.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Agent extends ClientSDK {
  /**
   * Run Agent
   *
   * @remarks
   * Run a loop with Anthropic's computer use agent to perform tasks on the VM.
   *
   * Requires API key authentication.
   */
  async run(
    request: operations.RunRequest,
    options?: RequestOptions,
  ): Promise<components.StandardResponse> {
    return unwrapAsync(agentRun(
      this,
      request,
      options,
    ));
  }

  /**
   * Stop Agent
   *
   * @remarks
   * Stop a running agent for a specific instance.
   *
   * Requires API key authentication.
   */
  async stop(
    request: operations.StopRequest,
    options?: RequestOptions,
  ): Promise<components.StandardResponse> {
    return unwrapAsync(agentStop(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Agent State
   *
   * @remarks
   * Get the current status of an agent for a specific instance.
   *
   * Requires API key authentication.
   */
  async status(
    request: operations.StatusRequest,
    options?: RequestOptions,
  ): Promise<components.AgentStatusResponse> {
    return unwrapAsync(agentStatus(
      this,
      request,
      options,
    ));
  }
}
