/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filesDownload } from "../funcs/filesDownload.js";
import { filesUpload } from "../funcs/filesUpload.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Files extends ClientSDK {
  /**
   * Upload To Vm
   *
   * @remarks
   * Upload a file from S3 to the VM
   *
   * Takes an S3 URL (often from FileUploader component) and transfers it to the VM.
   * Updates the files.uploads array in the vm_instances table to track the file.
   *
   * Requires API key authentication.
   */
  async upload(
    instanceId: string,
    s3VMUploadRequest: components.S3VMUploadRequest,
    options?: RequestOptions,
  ): Promise<components.FileUploadResponse> {
    return unwrapAsync(filesUpload(
      this,
      instanceId,
      s3VMUploadRequest,
      options,
    ));
  }

  /**
   * Get File
   *
   * @remarks
   * Get a secure download link for a file on the instance
   *
   * Generates a presigned S3 URL for the client to download the file directly
   *
   * Requires API key authentication.
   */
  async download(
    instanceId: string,
    requestBody: { [k: string]: string },
    options?: RequestOptions,
  ): Promise<components.FileDownloadResponse> {
    return unwrapAsync(filesDownload(
      this,
      instanceId,
      requestBody,
      options,
    ));
  }
}
