/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { interactClick } from "../funcs/interactClick.js";
import { interactDrag } from "../funcs/interactDrag.js";
import { interactGetFile } from "../funcs/interactGetFile.js";
import { interactInstall } from "../funcs/interactInstall.js";
import { interactKeypress } from "../funcs/interactKeypress.js";
import { interactMove } from "../funcs/interactMove.js";
import { interactScreenshot } from "../funcs/interactScreenshot.js";
import { interactScroll } from "../funcs/interactScroll.js";
import { interactType } from "../funcs/interactType.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Interact extends ClientSDK {
  /**
   * Install Chocolatey Packages
   *
   * @remarks
   * Install Chocolatey packages on a Windows instance. Find a list of packages here: https://community.chocolatey.org/packages.
   *
   * Requires API key authentication.
   */
  async install(
    request: operations.InstallRequest,
    options?: RequestOptions,
  ): Promise<components.PackageInstallResponse> {
    return unwrapAsync(interactInstall(
      this,
      request,
      options,
    ));
  }

  /**
   * Click
   *
   * @remarks
   * Perform a click operation at the specified coordinates or current position
   *
   * - If x and y are provided, click at those coordinates
   * - If x and y are omitted, click at the current cursor position
   * - Use button="left", clicks=1 for a single left click
   * - Use button="right", clicks=1 for a right click
   * - Use button="middle", clicks=1 for a middle click
   * - Use button="left", clicks=2 for a double click
   *
   * Requires API key authentication.
   */
  async click(
    request: operations.ClickRequest,
    options?: RequestOptions,
  ): Promise<components.StandardResponse> {
    return unwrapAsync(interactClick(
      this,
      request,
      options,
    ));
  }

  /**
   * Drag
   *
   * @remarks
   * Perform a drag operation along a path of coordinates
   *
   * - path: List of points to drag through, each with 'x' and 'y' coordinates
   * - button: Mouse button to use for dragging (default: "left")
   *
   * Requires API key authentication.
   */
  async drag(
    request: operations.DragRequest,
    options?: RequestOptions,
  ): Promise<components.StandardResponse> {
    return unwrapAsync(interactDrag(
      this,
      request,
      options,
    ));
  }

  /**
   * Take Screenshot
   *
   * @remarks
   * Take a screenshot of the instance
   *
   * Requires API key authentication.
   */
  async screenshot(
    request: operations.ScreenshotRequest,
    options?: RequestOptions,
  ): Promise<any> {
    return unwrapAsync(interactScreenshot(
      this,
      request,
      options,
    ));
  }

  /**
   * Move Mouse
   *
   * @remarks
   * Move the mouse to the specified coordinates
   *
   * Requires API key authentication.
   */
  async move(
    request: operations.MoveRequest,
    options?: RequestOptions,
  ): Promise<components.StandardResponse> {
    return unwrapAsync(interactMove(
      this,
      request,
      options,
    ));
  }

  /**
   * Keypress
   *
   * @remarks
   * Press the specified keys simultaneously (e.g. ['ctrl', 'alt', 'delete'])
   *
   * Requires API key authentication.
   */
  async keypress(
    request: operations.KeypressRequest,
    options?: RequestOptions,
  ): Promise<components.StandardResponse> {
    return unwrapAsync(interactKeypress(
      this,
      request,
      options,
    ));
  }

  /**
   * Type Text
   *
   * @remarks
   * Type the specified text with optional delay between keystrokes
   *
   * Requires API key authentication.
   */
  async type(
    request: operations.TypeRequest,
    options?: RequestOptions,
  ): Promise<components.StandardResponse> {
    return unwrapAsync(interactType(
      this,
      request,
      options,
    ));
  }

  /**
   * Scroll
   *
   * @remarks
   * Scroll at the specified coordinates
   *
   * Requires API key authentication.
   */
  async scroll(
    request: operations.ScrollRequest,
    options?: RequestOptions,
  ): Promise<components.StandardResponse> {
    return unwrapAsync(interactScroll(
      this,
      request,
      options,
    ));
  }

  /**
   * Get File
   *
   * @remarks
   * Get a secure download link for a file on the instance
   *
   * Generates a presigned S3 URL for the client to download the file directly
   *
   * Requires API key authentication.
   */
  async getFile(
    request: operations.GetFileRequest,
    options?: RequestOptions,
  ): Promise<operations.GetFileResponse200GetFile> {
    return unwrapAsync(interactGetFile(
      this,
      request,
      options,
    ));
  }
}
