/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Agent } from "./agent.js";
import { Files } from "./files.js";
import { Interact } from "./interact.js";
import { Windows } from "./windows.js";

export class Skylight extends ClientSDK {
  private _windows?: Windows;
  get windows(): Windows {
    return (this._windows ??= new Windows(this._options));
  }

  private _interact?: Interact;
  get interact(): Interact {
    return (this._interact ??= new Interact(this._options));
  }

  private _agent?: Agent;
  get agent(): Agent {
    return (this._agent ??= new Agent(this._options));
  }

  private _files?: Files;
  get files(): Files {
    return (this._files ??= new Files(this._options));
  }
}
