/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { windowsInstances } from "../funcs/windowsInstances.js";
import { windowsPause } from "../funcs/windowsPause.js";
import { windowsResume } from "../funcs/windowsResume.js";
import { windowsStart } from "../funcs/windowsStart.js";
import { windowsState } from "../funcs/windowsState.js";
import { windowsTerminate } from "../funcs/windowsTerminate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Windows extends ClientSDK {
  /**
   * Start Vm
   *
   * @remarks
   * Start a new Windows VM instance.
   *
   * - timeout_minutes: Optional timeout in minutes (default: 60)
   *
   * Requires API key authentication.
   */
  async start(
    request: components.InstanceRequest,
    options?: RequestOptions,
  ): Promise<components.InstanceStartResponse> {
    return unwrapAsync(windowsStart(
      this,
      request,
      options,
    ));
  }

  /**
   * Pause Vm
   *
   * @remarks
   * Requires API key authentication.
   */
  async pause(
    request: operations.PauseRequest,
    options?: RequestOptions,
  ): Promise<components.InstanceOperationResponse> {
    return unwrapAsync(windowsPause(
      this,
      request,
      options,
    ));
  }

  /**
   * Resume Vm
   *
   * @remarks
   * Requires API key authentication.
   */
  async resume(
    request: operations.ResumeRequest,
    options?: RequestOptions,
  ): Promise<components.InstanceOperationResponse> {
    return unwrapAsync(windowsResume(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Vm Status
   *
   * @remarks
   * Requires API key authentication.
   */
  async state(
    request: operations.StateRequest,
    options?: RequestOptions,
  ): Promise<components.InstanceStatusResponse> {
    return unwrapAsync(windowsState(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Instances
   *
   * @remarks
   * Requires API key authentication.
   */
  async instances(
    options?: RequestOptions,
  ): Promise<components.InstancesListResponse> {
    return unwrapAsync(windowsInstances(
      this,
      options,
    ));
  }

  /**
   * Terminate Vm
   *
   * @remarks
   * Requires API key authentication.
   */
  async terminate(
    request: operations.TerminateRequest,
    options?: RequestOptions,
  ): Promise<components.InstanceOperationResponse> {
    return unwrapAsync(windowsTerminate(
      this,
      request,
      options,
    ));
  }
}
