/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AnswerResponse = {};

export type AnswerRequest = {
  agentId: string;
  requestBody: AnswerResponse;
};

/** @internal */
export const AnswerResponse$inboundSchema: z.ZodType<
  AnswerResponse,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type AnswerResponse$Outbound = {};

/** @internal */
export const AnswerResponse$outboundSchema: z.ZodType<
  AnswerResponse$Outbound,
  z.ZodTypeDef,
  AnswerResponse
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AnswerResponse$ {
  /** @deprecated use `AnswerResponse$inboundSchema` instead. */
  export const inboundSchema = AnswerResponse$inboundSchema;
  /** @deprecated use `AnswerResponse$outboundSchema` instead. */
  export const outboundSchema = AnswerResponse$outboundSchema;
  /** @deprecated use `AnswerResponse$Outbound` instead. */
  export type Outbound = AnswerResponse$Outbound;
}

export function answerResponseToJSON(answerResponse: AnswerResponse): string {
  return JSON.stringify(AnswerResponse$outboundSchema.parse(answerResponse));
}

export function answerResponseFromJSON(
  jsonString: string,
): SafeParseResult<AnswerResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnswerResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnswerResponse' from JSON`,
  );
}

/** @internal */
export const AnswerRequest$inboundSchema: z.ZodType<
  AnswerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  agent_id: z.string(),
  RequestBody: z.lazy(() => AnswerResponse$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "agent_id": "agentId",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type AnswerRequest$Outbound = {
  agent_id: string;
  RequestBody: AnswerResponse$Outbound;
};

/** @internal */
export const AnswerRequest$outboundSchema: z.ZodType<
  AnswerRequest$Outbound,
  z.ZodTypeDef,
  AnswerRequest
> = z.object({
  agentId: z.string(),
  requestBody: z.lazy(() => AnswerResponse$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    agentId: "agent_id",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AnswerRequest$ {
  /** @deprecated use `AnswerRequest$inboundSchema` instead. */
  export const inboundSchema = AnswerRequest$inboundSchema;
  /** @deprecated use `AnswerRequest$outboundSchema` instead. */
  export const outboundSchema = AnswerRequest$outboundSchema;
  /** @deprecated use `AnswerRequest$Outbound` instead. */
  export type Outbound = AnswerRequest$Outbound;
}

export function answerRequestToJSON(answerRequest: AnswerRequest): string {
  return JSON.stringify(AnswerRequest$outboundSchema.parse(answerRequest));
}

export function answerRequestFromJSON(
  jsonString: string,
): SafeParseResult<AnswerRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnswerRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnswerRequest' from JSON`,
  );
}
