/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ClickRequest = {
  instanceId: string;
  clickRequest: components.ClickRequest;
};

/** @internal */
export const ClickRequest$inboundSchema: z.ZodType<
  ClickRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  instance_id: z.string(),
  ClickRequest: components.ClickRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "instance_id": "instanceId",
    "ClickRequest": "clickRequest",
  });
});

/** @internal */
export type ClickRequest$Outbound = {
  instance_id: string;
  ClickRequest: components.ClickRequest$Outbound;
};

/** @internal */
export const ClickRequest$outboundSchema: z.ZodType<
  ClickRequest$Outbound,
  z.ZodTypeDef,
  ClickRequest
> = z.object({
  instanceId: z.string(),
  clickRequest: components.ClickRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    instanceId: "instance_id",
    clickRequest: "ClickRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ClickRequest$ {
  /** @deprecated use `ClickRequest$inboundSchema` instead. */
  export const inboundSchema = ClickRequest$inboundSchema;
  /** @deprecated use `ClickRequest$outboundSchema` instead. */
  export const outboundSchema = ClickRequest$outboundSchema;
  /** @deprecated use `ClickRequest$Outbound` instead. */
  export type Outbound = ClickRequest$Outbound;
}

export function clickRequestToJSON(clickRequest: ClickRequest): string {
  return JSON.stringify(ClickRequest$outboundSchema.parse(clickRequest));
}

export function clickRequestFromJSON(
  jsonString: string,
): SafeParseResult<ClickRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClickRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClickRequest' from JSON`,
  );
}
