/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DownloadRequest = {
  instanceId: string;
  requestBody: { [k: string]: string };
};

/** @internal */
export const DownloadRequest$inboundSchema: z.ZodType<
  DownloadRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  instance_id: z.string(),
  RequestBody: z.record(z.string()),
}).transform((v) => {
  return remap$(v, {
    "instance_id": "instanceId",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type DownloadRequest$Outbound = {
  instance_id: string;
  RequestBody: { [k: string]: string };
};

/** @internal */
export const DownloadRequest$outboundSchema: z.ZodType<
  DownloadRequest$Outbound,
  z.ZodTypeDef,
  DownloadRequest
> = z.object({
  instanceId: z.string(),
  requestBody: z.record(z.string()),
}).transform((v) => {
  return remap$(v, {
    instanceId: "instance_id",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DownloadRequest$ {
  /** @deprecated use `DownloadRequest$inboundSchema` instead. */
  export const inboundSchema = DownloadRequest$inboundSchema;
  /** @deprecated use `DownloadRequest$outboundSchema` instead. */
  export const outboundSchema = DownloadRequest$outboundSchema;
  /** @deprecated use `DownloadRequest$Outbound` instead. */
  export type Outbound = DownloadRequest$Outbound;
}

export function downloadRequestToJSON(
  downloadRequest: DownloadRequest,
): string {
  return JSON.stringify(DownloadRequest$outboundSchema.parse(downloadRequest));
}

export function downloadRequestFromJSON(
  jsonString: string,
): SafeParseResult<DownloadRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DownloadRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DownloadRequest' from JSON`,
  );
}
