/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DragRequest = {
  instanceId: string;
  dragRequest: components.DragRequest;
};

/** @internal */
export const DragRequest$inboundSchema: z.ZodType<
  DragRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  instance_id: z.string(),
  DragRequest: components.DragRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "instance_id": "instanceId",
    "DragRequest": "dragRequest",
  });
});

/** @internal */
export type DragRequest$Outbound = {
  instance_id: string;
  DragRequest: components.DragRequest$Outbound;
};

/** @internal */
export const DragRequest$outboundSchema: z.ZodType<
  DragRequest$Outbound,
  z.ZodTypeDef,
  DragRequest
> = z.object({
  instanceId: z.string(),
  dragRequest: components.DragRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    instanceId: "instance_id",
    dragRequest: "DragRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DragRequest$ {
  /** @deprecated use `DragRequest$inboundSchema` instead. */
  export const inboundSchema = DragRequest$inboundSchema;
  /** @deprecated use `DragRequest$outboundSchema` instead. */
  export const outboundSchema = DragRequest$outboundSchema;
  /** @deprecated use `DragRequest$Outbound` instead. */
  export type Outbound = DragRequest$Outbound;
}

export function dragRequestToJSON(dragRequest: DragRequest): string {
  return JSON.stringify(DragRequest$outboundSchema.parse(dragRequest));
}

export function dragRequestFromJSON(
  jsonString: string,
): SafeParseResult<DragRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DragRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DragRequest' from JSON`,
  );
}
