/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type InstallRequest = {
  instanceId: string;
  packageInstallRequest: components.PackageInstallRequest;
};

/** @internal */
export const InstallRequest$inboundSchema: z.ZodType<
  InstallRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  instance_id: z.string(),
  PackageInstallRequest: components.PackageInstallRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "instance_id": "instanceId",
    "PackageInstallRequest": "packageInstallRequest",
  });
});

/** @internal */
export type InstallRequest$Outbound = {
  instance_id: string;
  PackageInstallRequest: components.PackageInstallRequest$Outbound;
};

/** @internal */
export const InstallRequest$outboundSchema: z.ZodType<
  InstallRequest$Outbound,
  z.ZodTypeDef,
  InstallRequest
> = z.object({
  instanceId: z.string(),
  packageInstallRequest: components.PackageInstallRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    instanceId: "instance_id",
    packageInstallRequest: "PackageInstallRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InstallRequest$ {
  /** @deprecated use `InstallRequest$inboundSchema` instead. */
  export const inboundSchema = InstallRequest$inboundSchema;
  /** @deprecated use `InstallRequest$outboundSchema` instead. */
  export const outboundSchema = InstallRequest$outboundSchema;
  /** @deprecated use `InstallRequest$Outbound` instead. */
  export type Outbound = InstallRequest$Outbound;
}

export function installRequestToJSON(installRequest: InstallRequest): string {
  return JSON.stringify(InstallRequest$outboundSchema.parse(installRequest));
}

export function installRequestFromJSON(
  jsonString: string,
): SafeParseResult<InstallRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InstallRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InstallRequest' from JSON`,
  );
}
