/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type KeypressRequest = {
  instanceId: string;
  keyRequest: components.KeyRequest;
};

/** @internal */
export const KeypressRequest$inboundSchema: z.ZodType<
  KeypressRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  instance_id: z.string(),
  KeyRequest: components.KeyRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "instance_id": "instanceId",
    "KeyRequest": "keyRequest",
  });
});

/** @internal */
export type KeypressRequest$Outbound = {
  instance_id: string;
  KeyRequest: components.KeyRequest$Outbound;
};

/** @internal */
export const KeypressRequest$outboundSchema: z.ZodType<
  KeypressRequest$Outbound,
  z.ZodTypeDef,
  KeypressRequest
> = z.object({
  instanceId: z.string(),
  keyRequest: components.KeyRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    instanceId: "instance_id",
    keyRequest: "KeyRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace KeypressRequest$ {
  /** @deprecated use `KeypressRequest$inboundSchema` instead. */
  export const inboundSchema = KeypressRequest$inboundSchema;
  /** @deprecated use `KeypressRequest$outboundSchema` instead. */
  export const outboundSchema = KeypressRequest$outboundSchema;
  /** @deprecated use `KeypressRequest$Outbound` instead. */
  export type Outbound = KeypressRequest$Outbound;
}

export function keypressRequestToJSON(
  keypressRequest: KeypressRequest,
): string {
  return JSON.stringify(KeypressRequest$outboundSchema.parse(keypressRequest));
}

export function keypressRequestFromJSON(
  jsonString: string,
): SafeParseResult<KeypressRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KeypressRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KeypressRequest' from JSON`,
  );
}
