/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MoveRequest = {
  instanceId: string;
  mouseMoveRequest: components.MouseMoveRequest;
};

/** @internal */
export const MoveRequest$inboundSchema: z.ZodType<
  MoveRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  instance_id: z.string(),
  MouseMoveRequest: components.MouseMoveRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "instance_id": "instanceId",
    "MouseMoveRequest": "mouseMoveRequest",
  });
});

/** @internal */
export type MoveRequest$Outbound = {
  instance_id: string;
  MouseMoveRequest: components.MouseMoveRequest$Outbound;
};

/** @internal */
export const MoveRequest$outboundSchema: z.ZodType<
  MoveRequest$Outbound,
  z.ZodTypeDef,
  MoveRequest
> = z.object({
  instanceId: z.string(),
  mouseMoveRequest: components.MouseMoveRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    instanceId: "instance_id",
    mouseMoveRequest: "MouseMoveRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MoveRequest$ {
  /** @deprecated use `MoveRequest$inboundSchema` instead. */
  export const inboundSchema = MoveRequest$inboundSchema;
  /** @deprecated use `MoveRequest$outboundSchema` instead. */
  export const outboundSchema = MoveRequest$outboundSchema;
  /** @deprecated use `MoveRequest$Outbound` instead. */
  export type Outbound = MoveRequest$Outbound;
}

export function moveRequestToJSON(moveRequest: MoveRequest): string {
  return JSON.stringify(MoveRequest$outboundSchema.parse(moveRequest));
}

export function moveRequestFromJSON(
  jsonString: string,
): SafeParseResult<MoveRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MoveRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MoveRequest' from JSON`,
  );
}
