/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PauseRequest = {
  instanceId: string;
};

/** @internal */
export const PauseRequest$inboundSchema: z.ZodType<
  PauseRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  instance_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "instance_id": "instanceId",
  });
});

/** @internal */
export type PauseRequest$Outbound = {
  instance_id: string;
};

/** @internal */
export const PauseRequest$outboundSchema: z.ZodType<
  PauseRequest$Outbound,
  z.ZodTypeDef,
  PauseRequest
> = z.object({
  instanceId: z.string(),
}).transform((v) => {
  return remap$(v, {
    instanceId: "instance_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PauseRequest$ {
  /** @deprecated use `PauseRequest$inboundSchema` instead. */
  export const inboundSchema = PauseRequest$inboundSchema;
  /** @deprecated use `PauseRequest$outboundSchema` instead. */
  export const outboundSchema = PauseRequest$outboundSchema;
  /** @deprecated use `PauseRequest$Outbound` instead. */
  export type Outbound = PauseRequest$Outbound;
}

export function pauseRequestToJSON(pauseRequest: PauseRequest): string {
  return JSON.stringify(PauseRequest$outboundSchema.parse(pauseRequest));
}

export function pauseRequestFromJSON(
  jsonString: string,
): SafeParseResult<PauseRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PauseRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PauseRequest' from JSON`,
  );
}
