/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ResumeRequest = {
  instanceId: string;
};

/** @internal */
export const ResumeRequest$inboundSchema: z.ZodType<
  ResumeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  instance_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "instance_id": "instanceId",
  });
});

/** @internal */
export type ResumeRequest$Outbound = {
  instance_id: string;
};

/** @internal */
export const ResumeRequest$outboundSchema: z.ZodType<
  ResumeRequest$Outbound,
  z.ZodTypeDef,
  ResumeRequest
> = z.object({
  instanceId: z.string(),
}).transform((v) => {
  return remap$(v, {
    instanceId: "instance_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResumeRequest$ {
  /** @deprecated use `ResumeRequest$inboundSchema` instead. */
  export const inboundSchema = ResumeRequest$inboundSchema;
  /** @deprecated use `ResumeRequest$outboundSchema` instead. */
  export const outboundSchema = ResumeRequest$outboundSchema;
  /** @deprecated use `ResumeRequest$Outbound` instead. */
  export type Outbound = ResumeRequest$Outbound;
}

export function resumeRequestToJSON(resumeRequest: ResumeRequest): string {
  return JSON.stringify(ResumeRequest$outboundSchema.parse(resumeRequest));
}

export function resumeRequestFromJSON(
  jsonString: string,
): SafeParseResult<ResumeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResumeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResumeRequest' from JSON`,
  );
}
