/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RunRequest = {
  instanceId: string;
  claudeRequest: components.ClaudeRequest;
};

/** @internal */
export const RunRequest$inboundSchema: z.ZodType<
  RunRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  instance_id: z.string(),
  ClaudeRequest: components.ClaudeRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "instance_id": "instanceId",
    "ClaudeRequest": "claudeRequest",
  });
});

/** @internal */
export type RunRequest$Outbound = {
  instance_id: string;
  ClaudeRequest: components.ClaudeRequest$Outbound;
};

/** @internal */
export const RunRequest$outboundSchema: z.ZodType<
  RunRequest$Outbound,
  z.ZodTypeDef,
  RunRequest
> = z.object({
  instanceId: z.string(),
  claudeRequest: components.ClaudeRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    instanceId: "instance_id",
    claudeRequest: "ClaudeRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RunRequest$ {
  /** @deprecated use `RunRequest$inboundSchema` instead. */
  export const inboundSchema = RunRequest$inboundSchema;
  /** @deprecated use `RunRequest$outboundSchema` instead. */
  export const outboundSchema = RunRequest$outboundSchema;
  /** @deprecated use `RunRequest$Outbound` instead. */
  export type Outbound = RunRequest$Outbound;
}

export function runRequestToJSON(runRequest: RunRequest): string {
  return JSON.stringify(RunRequest$outboundSchema.parse(runRequest));
}

export function runRequestFromJSON(
  jsonString: string,
): SafeParseResult<RunRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RunRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RunRequest' from JSON`,
  );
}
