/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ScreenshotRequest = {
  instanceId: string;
};

/** @internal */
export const ScreenshotRequest$inboundSchema: z.ZodType<
  ScreenshotRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  instance_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "instance_id": "instanceId",
  });
});

/** @internal */
export type ScreenshotRequest$Outbound = {
  instance_id: string;
};

/** @internal */
export const ScreenshotRequest$outboundSchema: z.ZodType<
  ScreenshotRequest$Outbound,
  z.ZodTypeDef,
  ScreenshotRequest
> = z.object({
  instanceId: z.string(),
}).transform((v) => {
  return remap$(v, {
    instanceId: "instance_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ScreenshotRequest$ {
  /** @deprecated use `ScreenshotRequest$inboundSchema` instead. */
  export const inboundSchema = ScreenshotRequest$inboundSchema;
  /** @deprecated use `ScreenshotRequest$outboundSchema` instead. */
  export const outboundSchema = ScreenshotRequest$outboundSchema;
  /** @deprecated use `ScreenshotRequest$Outbound` instead. */
  export type Outbound = ScreenshotRequest$Outbound;
}

export function screenshotRequestToJSON(
  screenshotRequest: ScreenshotRequest,
): string {
  return JSON.stringify(
    ScreenshotRequest$outboundSchema.parse(screenshotRequest),
  );
}

export function screenshotRequestFromJSON(
  jsonString: string,
): SafeParseResult<ScreenshotRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScreenshotRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScreenshotRequest' from JSON`,
  );
}
