/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ScrollRequest = {
  instanceId: string;
  scrollRequest: components.ScrollRequest;
};

/** @internal */
export const ScrollRequest$inboundSchema: z.ZodType<
  ScrollRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  instance_id: z.string(),
  ScrollRequest: components.ScrollRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "instance_id": "instanceId",
    "ScrollRequest": "scrollRequest",
  });
});

/** @internal */
export type ScrollRequest$Outbound = {
  instance_id: string;
  ScrollRequest: components.ScrollRequest$Outbound;
};

/** @internal */
export const ScrollRequest$outboundSchema: z.ZodType<
  ScrollRequest$Outbound,
  z.ZodTypeDef,
  ScrollRequest
> = z.object({
  instanceId: z.string(),
  scrollRequest: components.ScrollRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    instanceId: "instance_id",
    scrollRequest: "ScrollRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ScrollRequest$ {
  /** @deprecated use `ScrollRequest$inboundSchema` instead. */
  export const inboundSchema = ScrollRequest$inboundSchema;
  /** @deprecated use `ScrollRequest$outboundSchema` instead. */
  export const outboundSchema = ScrollRequest$outboundSchema;
  /** @deprecated use `ScrollRequest$Outbound` instead. */
  export type Outbound = ScrollRequest$Outbound;
}

export function scrollRequestToJSON(scrollRequest: ScrollRequest): string {
  return JSON.stringify(ScrollRequest$outboundSchema.parse(scrollRequest));
}

export function scrollRequestFromJSON(
  jsonString: string,
): SafeParseResult<ScrollRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScrollRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScrollRequest' from JSON`,
  );
}
