/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type StatusRequest = {
  agentId: string;
};

/** @internal */
export const StatusRequest$inboundSchema: z.ZodType<
  StatusRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  agent_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "agent_id": "agentId",
  });
});

/** @internal */
export type StatusRequest$Outbound = {
  agent_id: string;
};

/** @internal */
export const StatusRequest$outboundSchema: z.ZodType<
  StatusRequest$Outbound,
  z.ZodTypeDef,
  StatusRequest
> = z.object({
  agentId: z.string(),
}).transform((v) => {
  return remap$(v, {
    agentId: "agent_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StatusRequest$ {
  /** @deprecated use `StatusRequest$inboundSchema` instead. */
  export const inboundSchema = StatusRequest$inboundSchema;
  /** @deprecated use `StatusRequest$outboundSchema` instead. */
  export const outboundSchema = StatusRequest$outboundSchema;
  /** @deprecated use `StatusRequest$Outbound` instead. */
  export type Outbound = StatusRequest$Outbound;
}

export function statusRequestToJSON(statusRequest: StatusRequest): string {
  return JSON.stringify(StatusRequest$outboundSchema.parse(statusRequest));
}

export function statusRequestFromJSON(
  jsonString: string,
): SafeParseResult<StatusRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StatusRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StatusRequest' from JSON`,
  );
}
