/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type StateRequest = {
  instanceId: string;
};

/** @internal */
export const StateRequest$inboundSchema: z.ZodType<
  StateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  instance_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "instance_id": "instanceId",
  });
});

/** @internal */
export type StateRequest$Outbound = {
  instance_id: string;
};

/** @internal */
export const StateRequest$outboundSchema: z.ZodType<
  StateRequest$Outbound,
  z.ZodTypeDef,
  StateRequest
> = z.object({
  instanceId: z.string(),
}).transform((v) => {
  return remap$(v, {
    instanceId: "instance_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StateRequest$ {
  /** @deprecated use `StateRequest$inboundSchema` instead. */
  export const inboundSchema = StateRequest$inboundSchema;
  /** @deprecated use `StateRequest$outboundSchema` instead. */
  export const outboundSchema = StateRequest$outboundSchema;
  /** @deprecated use `StateRequest$Outbound` instead. */
  export type Outbound = StateRequest$Outbound;
}

export function stateRequestToJSON(stateRequest: StateRequest): string {
  return JSON.stringify(StateRequest$outboundSchema.parse(stateRequest));
}

export function stateRequestFromJSON(
  jsonString: string,
): SafeParseResult<StateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StateRequest' from JSON`,
  );
}
