/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type StopRequest = {
  instanceId: string;
};

/** @internal */
export const StopRequest$inboundSchema: z.ZodType<
  StopRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  instance_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "instance_id": "instanceId",
  });
});

/** @internal */
export type StopRequest$Outbound = {
  instance_id: string;
};

/** @internal */
export const StopRequest$outboundSchema: z.ZodType<
  StopRequest$Outbound,
  z.ZodTypeDef,
  StopRequest
> = z.object({
  instanceId: z.string(),
}).transform((v) => {
  return remap$(v, {
    instanceId: "instance_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StopRequest$ {
  /** @deprecated use `StopRequest$inboundSchema` instead. */
  export const inboundSchema = StopRequest$inboundSchema;
  /** @deprecated use `StopRequest$outboundSchema` instead. */
  export const outboundSchema = StopRequest$outboundSchema;
  /** @deprecated use `StopRequest$Outbound` instead. */
  export type Outbound = StopRequest$Outbound;
}

export function stopRequestToJSON(stopRequest: StopRequest): string {
  return JSON.stringify(StopRequest$outboundSchema.parse(stopRequest));
}

export function stopRequestFromJSON(
  jsonString: string,
): SafeParseResult<StopRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StopRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StopRequest' from JSON`,
  );
}
