/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TerminateRequest = {
  instanceId: string;
};

/** @internal */
export const TerminateRequest$inboundSchema: z.ZodType<
  TerminateRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  instance_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "instance_id": "instanceId",
  });
});

/** @internal */
export type TerminateRequest$Outbound = {
  instance_id: string;
};

/** @internal */
export const TerminateRequest$outboundSchema: z.ZodType<
  TerminateRequest$Outbound,
  z.ZodTypeDef,
  TerminateRequest
> = z.object({
  instanceId: z.string(),
}).transform((v) => {
  return remap$(v, {
    instanceId: "instance_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TerminateRequest$ {
  /** @deprecated use `TerminateRequest$inboundSchema` instead. */
  export const inboundSchema = TerminateRequest$inboundSchema;
  /** @deprecated use `TerminateRequest$outboundSchema` instead. */
  export const outboundSchema = TerminateRequest$outboundSchema;
  /** @deprecated use `TerminateRequest$Outbound` instead. */
  export type Outbound = TerminateRequest$Outbound;
}

export function terminateRequestToJSON(
  terminateRequest: TerminateRequest,
): string {
  return JSON.stringify(
    TerminateRequest$outboundSchema.parse(terminateRequest),
  );
}

export function terminateRequestFromJSON(
  jsonString: string,
): SafeParseResult<TerminateRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TerminateRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TerminateRequest' from JSON`,
  );
}
