/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TypeRequest = {
  instanceId: string;
  typeRequest: components.TypeRequest;
};

/** @internal */
export const TypeRequest$inboundSchema: z.ZodType<
  TypeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  instance_id: z.string(),
  TypeRequest: components.TypeRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "instance_id": "instanceId",
    "TypeRequest": "typeRequest",
  });
});

/** @internal */
export type TypeRequest$Outbound = {
  instance_id: string;
  TypeRequest: components.TypeRequest$Outbound;
};

/** @internal */
export const TypeRequest$outboundSchema: z.ZodType<
  TypeRequest$Outbound,
  z.ZodTypeDef,
  TypeRequest
> = z.object({
  instanceId: z.string(),
  typeRequest: components.TypeRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    instanceId: "instance_id",
    typeRequest: "TypeRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TypeRequest$ {
  /** @deprecated use `TypeRequest$inboundSchema` instead. */
  export const inboundSchema = TypeRequest$inboundSchema;
  /** @deprecated use `TypeRequest$outboundSchema` instead. */
  export const outboundSchema = TypeRequest$outboundSchema;
  /** @deprecated use `TypeRequest$Outbound` instead. */
  export type Outbound = TypeRequest$Outbound;
}

export function typeRequestToJSON(typeRequest: TypeRequest): string {
  return JSON.stringify(TypeRequest$outboundSchema.parse(typeRequest));
}

export function typeRequestFromJSON(
  jsonString: string,
): SafeParseResult<TypeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TypeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TypeRequest' from JSON`,
  );
}
