/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UploadRequest = {
  instanceId: string;
  s3VMUploadRequest: components.S3VMUploadRequest;
};

/** @internal */
export const UploadRequest$inboundSchema: z.ZodType<
  UploadRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  instance_id: z.string(),
  S3VMUploadRequest: components.S3VMUploadRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "instance_id": "instanceId",
    "S3VMUploadRequest": "s3VMUploadRequest",
  });
});

/** @internal */
export type UploadRequest$Outbound = {
  instance_id: string;
  S3VMUploadRequest: components.S3VMUploadRequest$Outbound;
};

/** @internal */
export const UploadRequest$outboundSchema: z.ZodType<
  UploadRequest$Outbound,
  z.ZodTypeDef,
  UploadRequest
> = z.object({
  instanceId: z.string(),
  s3VMUploadRequest: components.S3VMUploadRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    instanceId: "instance_id",
    s3VMUploadRequest: "S3VMUploadRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UploadRequest$ {
  /** @deprecated use `UploadRequest$inboundSchema` instead. */
  export const inboundSchema = UploadRequest$inboundSchema;
  /** @deprecated use `UploadRequest$outboundSchema` instead. */
  export const outboundSchema = UploadRequest$outboundSchema;
  /** @deprecated use `UploadRequest$Outbound` instead. */
  export type Outbound = UploadRequest$Outbound;
}

export function uploadRequestToJSON(uploadRequest: UploadRequest): string {
  return JSON.stringify(UploadRequest$outboundSchema.parse(uploadRequest));
}

export function uploadRequestFromJSON(
  jsonString: string,
): SafeParseResult<UploadRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UploadRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UploadRequest' from JSON`,
  );
}
