/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ActiveOperationResponse = {
  /**
   * Status of the operation
   */
  status: string;
  /**
   * Human-readable status message
   */
  message: string;
  /**
   * State of the instance (running, pending, hibernated, terminated)
   */
  state: string;
  /**
   * URL to livestream the instance
   */
  livestreamUrl: string;
};

/** @internal */
export const ActiveOperationResponse$inboundSchema: z.ZodType<
  ActiveOperationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string(),
  message: z.string(),
  state: z.string(),
  livestream_url: z.string(),
}).transform((v) => {
  return remap$(v, {
    "livestream_url": "livestreamUrl",
  });
});

/** @internal */
export type ActiveOperationResponse$Outbound = {
  status: string;
  message: string;
  state: string;
  livestream_url: string;
};

/** @internal */
export const ActiveOperationResponse$outboundSchema: z.ZodType<
  ActiveOperationResponse$Outbound,
  z.ZodTypeDef,
  ActiveOperationResponse
> = z.object({
  status: z.string(),
  message: z.string(),
  state: z.string(),
  livestreamUrl: z.string(),
}).transform((v) => {
  return remap$(v, {
    livestreamUrl: "livestream_url",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ActiveOperationResponse$ {
  /** @deprecated use `ActiveOperationResponse$inboundSchema` instead. */
  export const inboundSchema = ActiveOperationResponse$inboundSchema;
  /** @deprecated use `ActiveOperationResponse$outboundSchema` instead. */
  export const outboundSchema = ActiveOperationResponse$outboundSchema;
  /** @deprecated use `ActiveOperationResponse$Outbound` instead. */
  export type Outbound = ActiveOperationResponse$Outbound;
}

export function activeOperationResponseToJSON(
  activeOperationResponse: ActiveOperationResponse,
): string {
  return JSON.stringify(
    ActiveOperationResponse$outboundSchema.parse(activeOperationResponse),
  );
}

export function activeOperationResponseFromJSON(
  jsonString: string,
): SafeParseResult<ActiveOperationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActiveOperationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActiveOperationResponse' from JSON`,
  );
}
