/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Files = {};

export type AgentStatusResponse = {
  /**
   * Current status of the agent
   */
  agentStatus: string;
  /**
   * Whether the agent is currently running
   */
  isRunning: boolean;
  /**
   * Total number of steps executed
   */
  totalSteps: number;
  /**
   * Final summary of agent execution
   */
  finalSummary?: string | null | undefined;
  /**
   * List of files downloaded by the agent
   */
  files: Array<Files>;
  /**
   * List of steps executed by the agent
   */
  messages: Array<string>;
  /**
   * Timestamp when the agent was created
   */
  createdAt: string;
  /**
   * Original query given to the agent
   */
  query: string;
  /**
   * Unique identifier for the agent
   */
  agentId: string;
};

/** @internal */
export const Files$inboundSchema: z.ZodType<Files, z.ZodTypeDef, unknown> = z
  .object({});

/** @internal */
export type Files$Outbound = {};

/** @internal */
export const Files$outboundSchema: z.ZodType<
  Files$Outbound,
  z.ZodTypeDef,
  Files
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Files$ {
  /** @deprecated use `Files$inboundSchema` instead. */
  export const inboundSchema = Files$inboundSchema;
  /** @deprecated use `Files$outboundSchema` instead. */
  export const outboundSchema = Files$outboundSchema;
  /** @deprecated use `Files$Outbound` instead. */
  export type Outbound = Files$Outbound;
}

export function filesToJSON(files: Files): string {
  return JSON.stringify(Files$outboundSchema.parse(files));
}

export function filesFromJSON(
  jsonString: string,
): SafeParseResult<Files, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Files$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Files' from JSON`,
  );
}

/** @internal */
export const AgentStatusResponse$inboundSchema: z.ZodType<
  AgentStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  agent_status: z.string(),
  is_running: z.boolean(),
  total_steps: z.number().int(),
  final_summary: z.nullable(z.string()).optional(),
  files: z.array(z.lazy(() => Files$inboundSchema)),
  messages: z.array(z.string()),
  created_at: z.string(),
  query: z.string(),
  agent_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "agent_status": "agentStatus",
    "is_running": "isRunning",
    "total_steps": "totalSteps",
    "final_summary": "finalSummary",
    "created_at": "createdAt",
    "agent_id": "agentId",
  });
});

/** @internal */
export type AgentStatusResponse$Outbound = {
  agent_status: string;
  is_running: boolean;
  total_steps: number;
  final_summary?: string | null | undefined;
  files: Array<Files$Outbound>;
  messages: Array<string>;
  created_at: string;
  query: string;
  agent_id: string;
};

/** @internal */
export const AgentStatusResponse$outboundSchema: z.ZodType<
  AgentStatusResponse$Outbound,
  z.ZodTypeDef,
  AgentStatusResponse
> = z.object({
  agentStatus: z.string(),
  isRunning: z.boolean(),
  totalSteps: z.number().int(),
  finalSummary: z.nullable(z.string()).optional(),
  files: z.array(z.lazy(() => Files$outboundSchema)),
  messages: z.array(z.string()),
  createdAt: z.string(),
  query: z.string(),
  agentId: z.string(),
}).transform((v) => {
  return remap$(v, {
    agentStatus: "agent_status",
    isRunning: "is_running",
    totalSteps: "total_steps",
    finalSummary: "final_summary",
    createdAt: "created_at",
    agentId: "agent_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AgentStatusResponse$ {
  /** @deprecated use `AgentStatusResponse$inboundSchema` instead. */
  export const inboundSchema = AgentStatusResponse$inboundSchema;
  /** @deprecated use `AgentStatusResponse$outboundSchema` instead. */
  export const outboundSchema = AgentStatusResponse$outboundSchema;
  /** @deprecated use `AgentStatusResponse$Outbound` instead. */
  export type Outbound = AgentStatusResponse$Outbound;
}

export function agentStatusResponseToJSON(
  agentStatusResponse: AgentStatusResponse,
): string {
  return JSON.stringify(
    AgentStatusResponse$outboundSchema.parse(agentStatusResponse),
  );
}

export function agentStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<AgentStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentStatusResponse' from JSON`,
  );
}
