/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AgentStatusResponseFiles = {};

export type HumanInputRequest = {};

export type AgentStatusResponse = {
  /**
   * Current status of the agent
   */
  agentStatus: string;
  /**
   * Whether the agent is currently running
   */
  isRunning: boolean;
  /**
   * Total number of steps executed
   */
  totalSteps: number;
  /**
   * Final summary of agent execution
   */
  finalSummary?: string | null | undefined;
  /**
   * List of files downloaded by the agent
   */
  files: Array<AgentStatusResponseFiles>;
  /**
   * List of steps executed by the agent
   */
  messages: Array<string>;
  /**
   * Timestamp when the agent was created
   */
  createdAt: string;
  /**
   * Original query given to the agent
   */
  query: string;
  /**
   * Unique identifier for the agent
   */
  agentId: string;
  /**
   * Information about the human input being requested, if agent is waiting
   */
  humanInputRequest?: HumanInputRequest | null | undefined;
};

/** @internal */
export const AgentStatusResponseFiles$inboundSchema: z.ZodType<
  AgentStatusResponseFiles,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type AgentStatusResponseFiles$Outbound = {};

/** @internal */
export const AgentStatusResponseFiles$outboundSchema: z.ZodType<
  AgentStatusResponseFiles$Outbound,
  z.ZodTypeDef,
  AgentStatusResponseFiles
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AgentStatusResponseFiles$ {
  /** @deprecated use `AgentStatusResponseFiles$inboundSchema` instead. */
  export const inboundSchema = AgentStatusResponseFiles$inboundSchema;
  /** @deprecated use `AgentStatusResponseFiles$outboundSchema` instead. */
  export const outboundSchema = AgentStatusResponseFiles$outboundSchema;
  /** @deprecated use `AgentStatusResponseFiles$Outbound` instead. */
  export type Outbound = AgentStatusResponseFiles$Outbound;
}

export function agentStatusResponseFilesToJSON(
  agentStatusResponseFiles: AgentStatusResponseFiles,
): string {
  return JSON.stringify(
    AgentStatusResponseFiles$outboundSchema.parse(agentStatusResponseFiles),
  );
}

export function agentStatusResponseFilesFromJSON(
  jsonString: string,
): SafeParseResult<AgentStatusResponseFiles, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentStatusResponseFiles$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentStatusResponseFiles' from JSON`,
  );
}

/** @internal */
export const HumanInputRequest$inboundSchema: z.ZodType<
  HumanInputRequest,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type HumanInputRequest$Outbound = {};

/** @internal */
export const HumanInputRequest$outboundSchema: z.ZodType<
  HumanInputRequest$Outbound,
  z.ZodTypeDef,
  HumanInputRequest
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace HumanInputRequest$ {
  /** @deprecated use `HumanInputRequest$inboundSchema` instead. */
  export const inboundSchema = HumanInputRequest$inboundSchema;
  /** @deprecated use `HumanInputRequest$outboundSchema` instead. */
  export const outboundSchema = HumanInputRequest$outboundSchema;
  /** @deprecated use `HumanInputRequest$Outbound` instead. */
  export type Outbound = HumanInputRequest$Outbound;
}

export function humanInputRequestToJSON(
  humanInputRequest: HumanInputRequest,
): string {
  return JSON.stringify(
    HumanInputRequest$outboundSchema.parse(humanInputRequest),
  );
}

export function humanInputRequestFromJSON(
  jsonString: string,
): SafeParseResult<HumanInputRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HumanInputRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HumanInputRequest' from JSON`,
  );
}

/** @internal */
export const AgentStatusResponse$inboundSchema: z.ZodType<
  AgentStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  agent_status: z.string(),
  is_running: z.boolean(),
  total_steps: z.number().int(),
  final_summary: z.nullable(z.string()).optional(),
  files: z.array(z.lazy(() => AgentStatusResponseFiles$inboundSchema)),
  messages: z.array(z.string()),
  created_at: z.string(),
  query: z.string(),
  agent_id: z.string(),
  human_input_request: z.nullable(z.lazy(() => HumanInputRequest$inboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "agent_status": "agentStatus",
    "is_running": "isRunning",
    "total_steps": "totalSteps",
    "final_summary": "finalSummary",
    "created_at": "createdAt",
    "agent_id": "agentId",
    "human_input_request": "humanInputRequest",
  });
});

/** @internal */
export type AgentStatusResponse$Outbound = {
  agent_status: string;
  is_running: boolean;
  total_steps: number;
  final_summary?: string | null | undefined;
  files: Array<AgentStatusResponseFiles$Outbound>;
  messages: Array<string>;
  created_at: string;
  query: string;
  agent_id: string;
  human_input_request?: HumanInputRequest$Outbound | null | undefined;
};

/** @internal */
export const AgentStatusResponse$outboundSchema: z.ZodType<
  AgentStatusResponse$Outbound,
  z.ZodTypeDef,
  AgentStatusResponse
> = z.object({
  agentStatus: z.string(),
  isRunning: z.boolean(),
  totalSteps: z.number().int(),
  finalSummary: z.nullable(z.string()).optional(),
  files: z.array(z.lazy(() => AgentStatusResponseFiles$outboundSchema)),
  messages: z.array(z.string()),
  createdAt: z.string(),
  query: z.string(),
  agentId: z.string(),
  humanInputRequest: z.nullable(z.lazy(() => HumanInputRequest$outboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    agentStatus: "agent_status",
    isRunning: "is_running",
    totalSteps: "total_steps",
    finalSummary: "final_summary",
    createdAt: "created_at",
    agentId: "agent_id",
    humanInputRequest: "human_input_request",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AgentStatusResponse$ {
  /** @deprecated use `AgentStatusResponse$inboundSchema` instead. */
  export const inboundSchema = AgentStatusResponse$inboundSchema;
  /** @deprecated use `AgentStatusResponse$outboundSchema` instead. */
  export const outboundSchema = AgentStatusResponse$outboundSchema;
  /** @deprecated use `AgentStatusResponse$Outbound` instead. */
  export type Outbound = AgentStatusResponse$Outbound;
}

export function agentStatusResponseToJSON(
  agentStatusResponse: AgentStatusResponse,
): string {
  return JSON.stringify(
    AgentStatusResponse$outboundSchema.parse(agentStatusResponse),
  );
}

export function agentStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<AgentStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentStatusResponse' from JSON`,
  );
}
