/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Messages = {};

export type ClaudeRequest = {
  query: string;
  messages?: Array<Messages> | null | undefined;
};

/** @internal */
export const Messages$inboundSchema: z.ZodType<
  Messages,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type Messages$Outbound = {};

/** @internal */
export const Messages$outboundSchema: z.ZodType<
  Messages$Outbound,
  z.ZodTypeDef,
  Messages
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Messages$ {
  /** @deprecated use `Messages$inboundSchema` instead. */
  export const inboundSchema = Messages$inboundSchema;
  /** @deprecated use `Messages$outboundSchema` instead. */
  export const outboundSchema = Messages$outboundSchema;
  /** @deprecated use `Messages$Outbound` instead. */
  export type Outbound = Messages$Outbound;
}

export function messagesToJSON(messages: Messages): string {
  return JSON.stringify(Messages$outboundSchema.parse(messages));
}

export function messagesFromJSON(
  jsonString: string,
): SafeParseResult<Messages, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Messages$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Messages' from JSON`,
  );
}

/** @internal */
export const ClaudeRequest$inboundSchema: z.ZodType<
  ClaudeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  query: z.string(),
  messages: z.nullable(z.array(z.lazy(() => Messages$inboundSchema)))
    .optional(),
});

/** @internal */
export type ClaudeRequest$Outbound = {
  query: string;
  messages?: Array<Messages$Outbound> | null | undefined;
};

/** @internal */
export const ClaudeRequest$outboundSchema: z.ZodType<
  ClaudeRequest$Outbound,
  z.ZodTypeDef,
  ClaudeRequest
> = z.object({
  query: z.string(),
  messages: z.nullable(z.array(z.lazy(() => Messages$outboundSchema)))
    .optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ClaudeRequest$ {
  /** @deprecated use `ClaudeRequest$inboundSchema` instead. */
  export const inboundSchema = ClaudeRequest$inboundSchema;
  /** @deprecated use `ClaudeRequest$outboundSchema` instead. */
  export const outboundSchema = ClaudeRequest$outboundSchema;
  /** @deprecated use `ClaudeRequest$Outbound` instead. */
  export type Outbound = ClaudeRequest$Outbound;
}

export function claudeRequestToJSON(claudeRequest: ClaudeRequest): string {
  return JSON.stringify(ClaudeRequest$outboundSchema.parse(claudeRequest));
}

export function claudeRequestFromJSON(
  jsonString: string,
): SafeParseResult<ClaudeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClaudeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClaudeRequest' from JSON`,
  );
}
