/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const Button = {
  Left: "left",
  Right: "right",
  Middle: "middle",
} as const;
export type Button = ClosedEnum<typeof Button>;

export type ClickRequest = {
  x?: number | null | undefined;
  y?: number | null | undefined;
  button?: Button | undefined;
  clicks?: number | undefined;
};

/** @internal */
export const Button$inboundSchema: z.ZodNativeEnum<typeof Button> = z
  .nativeEnum(Button);

/** @internal */
export const Button$outboundSchema: z.ZodNativeEnum<typeof Button> =
  Button$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Button$ {
  /** @deprecated use `Button$inboundSchema` instead. */
  export const inboundSchema = Button$inboundSchema;
  /** @deprecated use `Button$outboundSchema` instead. */
  export const outboundSchema = Button$outboundSchema;
}

/** @internal */
export const ClickRequest$inboundSchema: z.ZodType<
  ClickRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  x: z.nullable(z.number().int()).optional(),
  y: z.nullable(z.number().int()).optional(),
  button: Button$inboundSchema.default("left"),
  clicks: z.number().int().default(1),
});

/** @internal */
export type ClickRequest$Outbound = {
  x?: number | null | undefined;
  y?: number | null | undefined;
  button: string;
  clicks: number;
};

/** @internal */
export const ClickRequest$outboundSchema: z.ZodType<
  ClickRequest$Outbound,
  z.ZodTypeDef,
  ClickRequest
> = z.object({
  x: z.nullable(z.number().int()).optional(),
  y: z.nullable(z.number().int()).optional(),
  button: Button$outboundSchema.default("left"),
  clicks: z.number().int().default(1),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ClickRequest$ {
  /** @deprecated use `ClickRequest$inboundSchema` instead. */
  export const inboundSchema = ClickRequest$inboundSchema;
  /** @deprecated use `ClickRequest$outboundSchema` instead. */
  export const outboundSchema = ClickRequest$outboundSchema;
  /** @deprecated use `ClickRequest$Outbound` instead. */
  export type Outbound = ClickRequest$Outbound;
}

export function clickRequestToJSON(clickRequest: ClickRequest): string {
  return JSON.stringify(ClickRequest$outboundSchema.parse(clickRequest));
}

export function clickRequestFromJSON(
  jsonString: string,
): SafeParseResult<ClickRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClickRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClickRequest' from JSON`,
  );
}
