/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const DragRequestButton = {
  Left: "left",
  Right: "right",
  Middle: "middle",
} as const;
export type DragRequestButton = ClosedEnum<typeof DragRequestButton>;

export type DragRequest = {
  path: Array<{ [k: string]: number }>;
  button?: DragRequestButton | undefined;
  /**
   * Optional step size for drag movements. If not provided, movement will be continuous.
   */
  step?: number | null | undefined;
};

/** @internal */
export const DragRequestButton$inboundSchema: z.ZodNativeEnum<
  typeof DragRequestButton
> = z.nativeEnum(DragRequestButton);

/** @internal */
export const DragRequestButton$outboundSchema: z.ZodNativeEnum<
  typeof DragRequestButton
> = DragRequestButton$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DragRequestButton$ {
  /** @deprecated use `DragRequestButton$inboundSchema` instead. */
  export const inboundSchema = DragRequestButton$inboundSchema;
  /** @deprecated use `DragRequestButton$outboundSchema` instead. */
  export const outboundSchema = DragRequestButton$outboundSchema;
}

/** @internal */
export const DragRequest$inboundSchema: z.ZodType<
  DragRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  path: z.array(z.record(z.number().int())),
  button: DragRequestButton$inboundSchema.default("left"),
  step: z.nullable(z.number().int()).optional(),
});

/** @internal */
export type DragRequest$Outbound = {
  path: Array<{ [k: string]: number }>;
  button: string;
  step?: number | null | undefined;
};

/** @internal */
export const DragRequest$outboundSchema: z.ZodType<
  DragRequest$Outbound,
  z.ZodTypeDef,
  DragRequest
> = z.object({
  path: z.array(z.record(z.number().int())),
  button: DragRequestButton$outboundSchema.default("left"),
  step: z.nullable(z.number().int()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DragRequest$ {
  /** @deprecated use `DragRequest$inboundSchema` instead. */
  export const inboundSchema = DragRequest$inboundSchema;
  /** @deprecated use `DragRequest$outboundSchema` instead. */
  export const outboundSchema = DragRequest$outboundSchema;
  /** @deprecated use `DragRequest$Outbound` instead. */
  export type Outbound = DragRequest$Outbound;
}

export function dragRequestToJSON(dragRequest: DragRequest): string {
  return JSON.stringify(DragRequest$outboundSchema.parse(dragRequest));
}

export function dragRequestFromJSON(
  jsonString: string,
): SafeParseResult<DragRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DragRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DragRequest' from JSON`,
  );
}
