/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Response containing a presigned URL to download a file
 */
export type FileDownloadResponse = {
  /**
   * Status of the operation
   */
  status: string;
  /**
   * Human-readable status message
   */
  message: string;
  /**
   * Presigned URL to download the file
   */
  downloadUrl: string;
};

/** @internal */
export const FileDownloadResponse$inboundSchema: z.ZodType<
  FileDownloadResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string(),
  message: z.string(),
  download_url: z.string(),
}).transform((v) => {
  return remap$(v, {
    "download_url": "downloadUrl",
  });
});

/** @internal */
export type FileDownloadResponse$Outbound = {
  status: string;
  message: string;
  download_url: string;
};

/** @internal */
export const FileDownloadResponse$outboundSchema: z.ZodType<
  FileDownloadResponse$Outbound,
  z.ZodTypeDef,
  FileDownloadResponse
> = z.object({
  status: z.string(),
  message: z.string(),
  downloadUrl: z.string(),
}).transform((v) => {
  return remap$(v, {
    downloadUrl: "download_url",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FileDownloadResponse$ {
  /** @deprecated use `FileDownloadResponse$inboundSchema` instead. */
  export const inboundSchema = FileDownloadResponse$inboundSchema;
  /** @deprecated use `FileDownloadResponse$outboundSchema` instead. */
  export const outboundSchema = FileDownloadResponse$outboundSchema;
  /** @deprecated use `FileDownloadResponse$Outbound` instead. */
  export type Outbound = FileDownloadResponse$Outbound;
}

export function fileDownloadResponseToJSON(
  fileDownloadResponse: FileDownloadResponse,
): string {
  return JSON.stringify(
    FileDownloadResponse$outboundSchema.parse(fileDownloadResponse),
  );
}

export function fileDownloadResponseFromJSON(
  jsonString: string,
): SafeParseResult<FileDownloadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FileDownloadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FileDownloadResponse' from JSON`,
  );
}
