/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Response when a file is successfully uploaded to a VM
 */
export type FileUploadResponse = {
  /**
   * Status of the operation
   */
  status: string;
  /**
   * Human-readable status message
   */
  message: string;
  /**
   * Path where the file was saved on the VM
   */
  filePath: string;
};

/** @internal */
export const FileUploadResponse$inboundSchema: z.ZodType<
  FileUploadResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string(),
  message: z.string(),
  file_path: z.string(),
}).transform((v) => {
  return remap$(v, {
    "file_path": "filePath",
  });
});

/** @internal */
export type FileUploadResponse$Outbound = {
  status: string;
  message: string;
  file_path: string;
};

/** @internal */
export const FileUploadResponse$outboundSchema: z.ZodType<
  FileUploadResponse$Outbound,
  z.ZodTypeDef,
  FileUploadResponse
> = z.object({
  status: z.string(),
  message: z.string(),
  filePath: z.string(),
}).transform((v) => {
  return remap$(v, {
    filePath: "file_path",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FileUploadResponse$ {
  /** @deprecated use `FileUploadResponse$inboundSchema` instead. */
  export const inboundSchema = FileUploadResponse$inboundSchema;
  /** @deprecated use `FileUploadResponse$outboundSchema` instead. */
  export const outboundSchema = FileUploadResponse$outboundSchema;
  /** @deprecated use `FileUploadResponse$Outbound` instead. */
  export type Outbound = FileUploadResponse$Outbound;
}

export function fileUploadResponseToJSON(
  fileUploadResponse: FileUploadResponse,
): string {
  return JSON.stringify(
    FileUploadResponse$outboundSchema.parse(fileUploadResponse),
  );
}

export function fileUploadResponseFromJSON(
  jsonString: string,
): SafeParseResult<FileUploadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FileUploadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FileUploadResponse' from JSON`,
  );
}
