/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type InactiveOperationResponse = {
  /**
   * Status of the operation
   */
  status: string;
  /**
   * Human-readable status message
   */
  message: string;
  /**
   * State of the instance (running, pending, hibernated, terminated)
   */
  state: string;
};

/** @internal */
export const InactiveOperationResponse$inboundSchema: z.ZodType<
  InactiveOperationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string(),
  message: z.string(),
  state: z.string(),
});

/** @internal */
export type InactiveOperationResponse$Outbound = {
  status: string;
  message: string;
  state: string;
};

/** @internal */
export const InactiveOperationResponse$outboundSchema: z.ZodType<
  InactiveOperationResponse$Outbound,
  z.ZodTypeDef,
  InactiveOperationResponse
> = z.object({
  status: z.string(),
  message: z.string(),
  state: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InactiveOperationResponse$ {
  /** @deprecated use `InactiveOperationResponse$inboundSchema` instead. */
  export const inboundSchema = InactiveOperationResponse$inboundSchema;
  /** @deprecated use `InactiveOperationResponse$outboundSchema` instead. */
  export const outboundSchema = InactiveOperationResponse$outboundSchema;
  /** @deprecated use `InactiveOperationResponse$Outbound` instead. */
  export type Outbound = InactiveOperationResponse$Outbound;
}

export function inactiveOperationResponseToJSON(
  inactiveOperationResponse: InactiveOperationResponse,
): string {
  return JSON.stringify(
    InactiveOperationResponse$outboundSchema.parse(inactiveOperationResponse),
  );
}

export function inactiveOperationResponseFromJSON(
  jsonString: string,
): SafeParseResult<InactiveOperationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InactiveOperationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InactiveOperationResponse' from JSON`,
  );
}
