/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Instances = {};

export type InstancesListResponse = {
  /**
   * List of instance IDs and states associated with the API key
   */
  instances: Array<Instances>;
};

/** @internal */
export const Instances$inboundSchema: z.ZodType<
  Instances,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type Instances$Outbound = {};

/** @internal */
export const Instances$outboundSchema: z.ZodType<
  Instances$Outbound,
  z.ZodTypeDef,
  Instances
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Instances$ {
  /** @deprecated use `Instances$inboundSchema` instead. */
  export const inboundSchema = Instances$inboundSchema;
  /** @deprecated use `Instances$outboundSchema` instead. */
  export const outboundSchema = Instances$outboundSchema;
  /** @deprecated use `Instances$Outbound` instead. */
  export type Outbound = Instances$Outbound;
}

export function instancesToJSON(instances: Instances): string {
  return JSON.stringify(Instances$outboundSchema.parse(instances));
}

export function instancesFromJSON(
  jsonString: string,
): SafeParseResult<Instances, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Instances$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Instances' from JSON`,
  );
}

/** @internal */
export const InstancesListResponse$inboundSchema: z.ZodType<
  InstancesListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  instances: z.array(z.lazy(() => Instances$inboundSchema)),
});

/** @internal */
export type InstancesListResponse$Outbound = {
  instances: Array<Instances$Outbound>;
};

/** @internal */
export const InstancesListResponse$outboundSchema: z.ZodType<
  InstancesListResponse$Outbound,
  z.ZodTypeDef,
  InstancesListResponse
> = z.object({
  instances: z.array(z.lazy(() => Instances$outboundSchema)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InstancesListResponse$ {
  /** @deprecated use `InstancesListResponse$inboundSchema` instead. */
  export const inboundSchema = InstancesListResponse$inboundSchema;
  /** @deprecated use `InstancesListResponse$outboundSchema` instead. */
  export const outboundSchema = InstancesListResponse$outboundSchema;
  /** @deprecated use `InstancesListResponse$Outbound` instead. */
  export type Outbound = InstancesListResponse$Outbound;
}

export function instancesListResponseToJSON(
  instancesListResponse: InstancesListResponse,
): string {
  return JSON.stringify(
    InstancesListResponse$outboundSchema.parse(instancesListResponse),
  );
}

export function instancesListResponseFromJSON(
  jsonString: string,
): SafeParseResult<InstancesListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InstancesListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InstancesListResponse' from JSON`,
  );
}
