/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type InstanceStartResponse = {
  /**
   * Unique identifier of the created instance
   */
  instanceId: string;
  /**
   * Human-readable status message
   */
  message: string;
  /**
   * URL to livestream the instance
   */
  livestreamUrl: string;
  /**
   * State of the instance (running, pending, hibernated, terminated)
   */
  state: string;
};

/** @internal */
export const InstanceStartResponse$inboundSchema: z.ZodType<
  InstanceStartResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  instance_id: z.string(),
  message: z.string(),
  livestream_url: z.string(),
  state: z.string(),
}).transform((v) => {
  return remap$(v, {
    "instance_id": "instanceId",
    "livestream_url": "livestreamUrl",
  });
});

/** @internal */
export type InstanceStartResponse$Outbound = {
  instance_id: string;
  message: string;
  livestream_url: string;
  state: string;
};

/** @internal */
export const InstanceStartResponse$outboundSchema: z.ZodType<
  InstanceStartResponse$Outbound,
  z.ZodTypeDef,
  InstanceStartResponse
> = z.object({
  instanceId: z.string(),
  message: z.string(),
  livestreamUrl: z.string(),
  state: z.string(),
}).transform((v) => {
  return remap$(v, {
    instanceId: "instance_id",
    livestreamUrl: "livestream_url",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InstanceStartResponse$ {
  /** @deprecated use `InstanceStartResponse$inboundSchema` instead. */
  export const inboundSchema = InstanceStartResponse$inboundSchema;
  /** @deprecated use `InstanceStartResponse$outboundSchema` instead. */
  export const outboundSchema = InstanceStartResponse$outboundSchema;
  /** @deprecated use `InstanceStartResponse$Outbound` instead. */
  export type Outbound = InstanceStartResponse$Outbound;
}

export function instanceStartResponseToJSON(
  instanceStartResponse: InstanceStartResponse,
): string {
  return JSON.stringify(
    InstanceStartResponse$outboundSchema.parse(instanceStartResponse),
  );
}

export function instanceStartResponseFromJSON(
  jsonString: string,
): SafeParseResult<InstanceStartResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InstanceStartResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InstanceStartResponse' from JSON`,
  );
}
