/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  InstanceStatusResponse,
  InstanceStatusResponse$inboundSchema,
  InstanceStatusResponse$Outbound,
  InstanceStatusResponse$outboundSchema,
} from "./instancestatusresponse.js";

export type InstancesListResponse = {
  /**
   * List of instances associated with the API key
   */
  instances: Array<InstanceStatusResponse>;
};

/** @internal */
export const InstancesListResponse$inboundSchema: z.ZodType<
  InstancesListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  instances: z.array(InstanceStatusResponse$inboundSchema),
});

/** @internal */
export type InstancesListResponse$Outbound = {
  instances: Array<InstanceStatusResponse$Outbound>;
};

/** @internal */
export const InstancesListResponse$outboundSchema: z.ZodType<
  InstancesListResponse$Outbound,
  z.ZodTypeDef,
  InstancesListResponse
> = z.object({
  instances: z.array(InstanceStatusResponse$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InstancesListResponse$ {
  /** @deprecated use `InstancesListResponse$inboundSchema` instead. */
  export const inboundSchema = InstancesListResponse$inboundSchema;
  /** @deprecated use `InstancesListResponse$outboundSchema` instead. */
  export const outboundSchema = InstancesListResponse$outboundSchema;
  /** @deprecated use `InstancesListResponse$Outbound` instead. */
  export type Outbound = InstancesListResponse$Outbound;
}

export function instancesListResponseToJSON(
  instancesListResponse: InstancesListResponse,
): string {
  return JSON.stringify(
    InstancesListResponse$outboundSchema.parse(instancesListResponse),
  );
}

export function instancesListResponseFromJSON(
  jsonString: string,
): SafeParseResult<InstancesListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InstancesListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InstancesListResponse' from JSON`,
  );
}
