/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type InstanceOperationResponse = {
  /**
   * Status of the operation
   */
  status: string;
  /**
   * Human-readable status message
   */
  message: string;
  /**
   * AWS state of the instance
   */
  awsState: string;
};

/** @internal */
export const InstanceOperationResponse$inboundSchema: z.ZodType<
  InstanceOperationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string(),
  message: z.string(),
  aws_state: z.string(),
}).transform((v) => {
  return remap$(v, {
    "aws_state": "awsState",
  });
});

/** @internal */
export type InstanceOperationResponse$Outbound = {
  status: string;
  message: string;
  aws_state: string;
};

/** @internal */
export const InstanceOperationResponse$outboundSchema: z.ZodType<
  InstanceOperationResponse$Outbound,
  z.ZodTypeDef,
  InstanceOperationResponse
> = z.object({
  status: z.string(),
  message: z.string(),
  awsState: z.string(),
}).transform((v) => {
  return remap$(v, {
    awsState: "aws_state",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InstanceOperationResponse$ {
  /** @deprecated use `InstanceOperationResponse$inboundSchema` instead. */
  export const inboundSchema = InstanceOperationResponse$inboundSchema;
  /** @deprecated use `InstanceOperationResponse$outboundSchema` instead. */
  export const outboundSchema = InstanceOperationResponse$outboundSchema;
  /** @deprecated use `InstanceOperationResponse$Outbound` instead. */
  export type Outbound = InstanceOperationResponse$Outbound;
}

export function instanceOperationResponseToJSON(
  instanceOperationResponse: InstanceOperationResponse,
): string {
  return JSON.stringify(
    InstanceOperationResponse$outboundSchema.parse(instanceOperationResponse),
  );
}

export function instanceOperationResponseFromJSON(
  jsonString: string,
): SafeParseResult<InstanceOperationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InstanceOperationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InstanceOperationResponse' from JSON`,
  );
}
