/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type InstanceStatusResponse = {
  /**
   * Current state of the instance
   */
  state: string;
};

/** @internal */
export const InstanceStatusResponse$inboundSchema: z.ZodType<
  InstanceStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  state: z.string(),
});

/** @internal */
export type InstanceStatusResponse$Outbound = {
  state: string;
};

/** @internal */
export const InstanceStatusResponse$outboundSchema: z.ZodType<
  InstanceStatusResponse$Outbound,
  z.ZodTypeDef,
  InstanceStatusResponse
> = z.object({
  state: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InstanceStatusResponse$ {
  /** @deprecated use `InstanceStatusResponse$inboundSchema` instead. */
  export const inboundSchema = InstanceStatusResponse$inboundSchema;
  /** @deprecated use `InstanceStatusResponse$outboundSchema` instead. */
  export const outboundSchema = InstanceStatusResponse$outboundSchema;
  /** @deprecated use `InstanceStatusResponse$Outbound` instead. */
  export type Outbound = InstanceStatusResponse$Outbound;
}

export function instanceStatusResponseToJSON(
  instanceStatusResponse: InstanceStatusResponse,
): string {
  return JSON.stringify(
    InstanceStatusResponse$outboundSchema.parse(instanceStatusResponse),
  );
}

export function instanceStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<InstanceStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InstanceStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InstanceStatusResponse' from JSON`,
  );
}
