/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type InstanceStatusResponse = {
  instanceId: string;
  /**
   * Current state of the instance
   */
  state: string;
  /**
   * Timeout in minutes before instance auto-termination
   */
  timeout: number;
  /**
   * Minutes used by the instance so far
   */
  usedMinutes: number;
  /**
   * Current knowledge of the instance
   */
  knowledge: string;
  /**
   * URL to livestream the instance
   */
  livestreamUrl: string;
  /**
   * When the instance was assigned
   */
  assignedAt?: string | null | undefined;
};

/** @internal */
export const InstanceStatusResponse$inboundSchema: z.ZodType<
  InstanceStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  instance_id: z.string(),
  state: z.string(),
  timeout: z.number().int(),
  used_minutes: z.number().int(),
  knowledge: z.string(),
  livestream_url: z.string(),
  assigned_at: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "instance_id": "instanceId",
    "used_minutes": "usedMinutes",
    "livestream_url": "livestreamUrl",
    "assigned_at": "assignedAt",
  });
});

/** @internal */
export type InstanceStatusResponse$Outbound = {
  instance_id: string;
  state: string;
  timeout: number;
  used_minutes: number;
  knowledge: string;
  livestream_url: string;
  assigned_at?: string | null | undefined;
};

/** @internal */
export const InstanceStatusResponse$outboundSchema: z.ZodType<
  InstanceStatusResponse$Outbound,
  z.ZodTypeDef,
  InstanceStatusResponse
> = z.object({
  instanceId: z.string(),
  state: z.string(),
  timeout: z.number().int(),
  usedMinutes: z.number().int(),
  knowledge: z.string(),
  livestreamUrl: z.string(),
  assignedAt: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    instanceId: "instance_id",
    usedMinutes: "used_minutes",
    livestreamUrl: "livestream_url",
    assignedAt: "assigned_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InstanceStatusResponse$ {
  /** @deprecated use `InstanceStatusResponse$inboundSchema` instead. */
  export const inboundSchema = InstanceStatusResponse$inboundSchema;
  /** @deprecated use `InstanceStatusResponse$outboundSchema` instead. */
  export const outboundSchema = InstanceStatusResponse$outboundSchema;
  /** @deprecated use `InstanceStatusResponse$Outbound` instead. */
  export type Outbound = InstanceStatusResponse$Outbound;
}

export function instanceStatusResponseToJSON(
  instanceStatusResponse: InstanceStatusResponse,
): string {
  return JSON.stringify(
    InstanceStatusResponse$outboundSchema.parse(instanceStatusResponse),
  );
}

export function instanceStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<InstanceStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InstanceStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InstanceStatusResponse' from JSON`,
  );
}
