/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type InstanceRequest = {
  /**
   * Optional API key for authentication
   */
  apiKey?: string | null | undefined;
  /**
   * Timeout in minutes before instance auto-termination
   */
  timeoutMinutes?: number | null | undefined;
};

/** @internal */
export const InstanceRequest$inboundSchema: z.ZodType<
  InstanceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  api_key: z.nullable(z.string()).optional(),
  timeout_minutes: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    "api_key": "apiKey",
    "timeout_minutes": "timeoutMinutes",
  });
});

/** @internal */
export type InstanceRequest$Outbound = {
  api_key?: string | null | undefined;
  timeout_minutes?: number | null | undefined;
};

/** @internal */
export const InstanceRequest$outboundSchema: z.ZodType<
  InstanceRequest$Outbound,
  z.ZodTypeDef,
  InstanceRequest
> = z.object({
  apiKey: z.nullable(z.string()).optional(),
  timeoutMinutes: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    apiKey: "api_key",
    timeoutMinutes: "timeout_minutes",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InstanceRequest$ {
  /** @deprecated use `InstanceRequest$inboundSchema` instead. */
  export const inboundSchema = InstanceRequest$inboundSchema;
  /** @deprecated use `InstanceRequest$outboundSchema` instead. */
  export const outboundSchema = InstanceRequest$outboundSchema;
  /** @deprecated use `InstanceRequest$Outbound` instead. */
  export type Outbound = InstanceRequest$Outbound;
}

export function instanceRequestToJSON(
  instanceRequest: InstanceRequest,
): string {
  return JSON.stringify(InstanceRequest$outboundSchema.parse(instanceRequest));
}

export function instanceRequestFromJSON(
  jsonString: string,
): SafeParseResult<InstanceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InstanceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InstanceRequest' from JSON`,
  );
}
