/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type KeyRequest = {
  keys: Array<string>;
};

/** @internal */
export const KeyRequest$inboundSchema: z.ZodType<
  KeyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  keys: z.array(z.string()),
});

/** @internal */
export type KeyRequest$Outbound = {
  keys: Array<string>;
};

/** @internal */
export const KeyRequest$outboundSchema: z.ZodType<
  KeyRequest$Outbound,
  z.ZodTypeDef,
  KeyRequest
> = z.object({
  keys: z.array(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace KeyRequest$ {
  /** @deprecated use `KeyRequest$inboundSchema` instead. */
  export const inboundSchema = KeyRequest$inboundSchema;
  /** @deprecated use `KeyRequest$outboundSchema` instead. */
  export const outboundSchema = KeyRequest$outboundSchema;
  /** @deprecated use `KeyRequest$Outbound` instead. */
  export type Outbound = KeyRequest$Outbound;
}

export function keyRequestToJSON(keyRequest: KeyRequest): string {
  return JSON.stringify(KeyRequest$outboundSchema.parse(keyRequest));
}

export function keyRequestFromJSON(
  jsonString: string,
): SafeParseResult<KeyRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KeyRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KeyRequest' from JSON`,
  );
}
