/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MouseMoveRequest = {
  x: number;
  y: number;
};

/** @internal */
export const MouseMoveRequest$inboundSchema: z.ZodType<
  MouseMoveRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  x: z.number().int(),
  y: z.number().int(),
});

/** @internal */
export type MouseMoveRequest$Outbound = {
  x: number;
  y: number;
};

/** @internal */
export const MouseMoveRequest$outboundSchema: z.ZodType<
  MouseMoveRequest$Outbound,
  z.ZodTypeDef,
  MouseMoveRequest
> = z.object({
  x: z.number().int(),
  y: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace MouseMoveRequest$ {
  /** @deprecated use `MouseMoveRequest$inboundSchema` instead. */
  export const inboundSchema = MouseMoveRequest$inboundSchema;
  /** @deprecated use `MouseMoveRequest$outboundSchema` instead. */
  export const outboundSchema = MouseMoveRequest$outboundSchema;
  /** @deprecated use `MouseMoveRequest$Outbound` instead. */
  export type Outbound = MouseMoveRequest$Outbound;
}

export function mouseMoveRequestToJSON(
  mouseMoveRequest: MouseMoveRequest,
): string {
  return JSON.stringify(
    MouseMoveRequest$outboundSchema.parse(mouseMoveRequest),
  );
}

export function mouseMoveRequestFromJSON(
  jsonString: string,
): SafeParseResult<MouseMoveRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MouseMoveRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MouseMoveRequest' from JSON`,
  );
}
