/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PackageInstallResponse = {
  /**
   * Status of the operation
   */
  status: string;
  /**
   * Human-readable status message
   */
  message: string;
  /**
   * AWS state of the instance
   */
  awsState: string;
  /**
   * Command ID for tracking installation progress
   */
  commandId?: string | null | undefined;
};

/** @internal */
export const PackageInstallResponse$inboundSchema: z.ZodType<
  PackageInstallResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string(),
  message: z.string(),
  aws_state: z.string(),
  command_id: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "aws_state": "awsState",
    "command_id": "commandId",
  });
});

/** @internal */
export type PackageInstallResponse$Outbound = {
  status: string;
  message: string;
  aws_state: string;
  command_id?: string | null | undefined;
};

/** @internal */
export const PackageInstallResponse$outboundSchema: z.ZodType<
  PackageInstallResponse$Outbound,
  z.ZodTypeDef,
  PackageInstallResponse
> = z.object({
  status: z.string(),
  message: z.string(),
  awsState: z.string(),
  commandId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    awsState: "aws_state",
    commandId: "command_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PackageInstallResponse$ {
  /** @deprecated use `PackageInstallResponse$inboundSchema` instead. */
  export const inboundSchema = PackageInstallResponse$inboundSchema;
  /** @deprecated use `PackageInstallResponse$outboundSchema` instead. */
  export const outboundSchema = PackageInstallResponse$outboundSchema;
  /** @deprecated use `PackageInstallResponse$Outbound` instead. */
  export type Outbound = PackageInstallResponse$Outbound;
}

export function packageInstallResponseToJSON(
  packageInstallResponse: PackageInstallResponse,
): string {
  return JSON.stringify(
    PackageInstallResponse$outboundSchema.parse(packageInstallResponse),
  );
}

export function packageInstallResponseFromJSON(
  jsonString: string,
): SafeParseResult<PackageInstallResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PackageInstallResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PackageInstallResponse' from JSON`,
  );
}
