/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PackageInstallRequest = {
  /**
   * List of Chocolatey package names to install
   */
  packages: Array<string>;
};

/** @internal */
export const PackageInstallRequest$inboundSchema: z.ZodType<
  PackageInstallRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  packages: z.array(z.string()),
});

/** @internal */
export type PackageInstallRequest$Outbound = {
  packages: Array<string>;
};

/** @internal */
export const PackageInstallRequest$outboundSchema: z.ZodType<
  PackageInstallRequest$Outbound,
  z.ZodTypeDef,
  PackageInstallRequest
> = z.object({
  packages: z.array(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PackageInstallRequest$ {
  /** @deprecated use `PackageInstallRequest$inboundSchema` instead. */
  export const inboundSchema = PackageInstallRequest$inboundSchema;
  /** @deprecated use `PackageInstallRequest$outboundSchema` instead. */
  export const outboundSchema = PackageInstallRequest$outboundSchema;
  /** @deprecated use `PackageInstallRequest$Outbound` instead. */
  export type Outbound = PackageInstallRequest$Outbound;
}

export function packageInstallRequestToJSON(
  packageInstallRequest: PackageInstallRequest,
): string {
  return JSON.stringify(
    PackageInstallRequest$outboundSchema.parse(packageInstallRequest),
  );
}

export function packageInstallRequestFromJSON(
  jsonString: string,
): SafeParseResult<PackageInstallRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PackageInstallRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PackageInstallRequest' from JSON`,
  );
}
