/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type S3VMUploadRequest = {
  /**
   * The S3 URL of the file to upload
   */
  s3Url: string;
  /**
   * Original name of the file
   */
  fileName: string;
  /**
   * MIME type of the file
   */
  fileType?: string | undefined;
  /**
   * Target path on the VM (defaults to Users/Administrator/Desktop/{file_name})
   */
  targetPath?: string | undefined;
};

/** @internal */
export const S3VMUploadRequest$inboundSchema: z.ZodType<
  S3VMUploadRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  s3_url: z.string(),
  file_name: z.string(),
  file_type: z.string().optional(),
  target_path: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "s3_url": "s3Url",
    "file_name": "fileName",
    "file_type": "fileType",
    "target_path": "targetPath",
  });
});

/** @internal */
export type S3VMUploadRequest$Outbound = {
  s3_url: string;
  file_name: string;
  file_type?: string | undefined;
  target_path?: string | undefined;
};

/** @internal */
export const S3VMUploadRequest$outboundSchema: z.ZodType<
  S3VMUploadRequest$Outbound,
  z.ZodTypeDef,
  S3VMUploadRequest
> = z.object({
  s3Url: z.string(),
  fileName: z.string(),
  fileType: z.string().optional(),
  targetPath: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    s3Url: "s3_url",
    fileName: "file_name",
    fileType: "file_type",
    targetPath: "target_path",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace S3VMUploadRequest$ {
  /** @deprecated use `S3VMUploadRequest$inboundSchema` instead. */
  export const inboundSchema = S3VMUploadRequest$inboundSchema;
  /** @deprecated use `S3VMUploadRequest$outboundSchema` instead. */
  export const outboundSchema = S3VMUploadRequest$outboundSchema;
  /** @deprecated use `S3VMUploadRequest$Outbound` instead. */
  export type Outbound = S3VMUploadRequest$Outbound;
}

export function s3VMUploadRequestToJSON(
  s3VMUploadRequest: S3VMUploadRequest,
): string {
  return JSON.stringify(
    S3VMUploadRequest$outboundSchema.parse(s3VMUploadRequest),
  );
}

export function s3VMUploadRequestFromJSON(
  jsonString: string,
): SafeParseResult<S3VMUploadRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => S3VMUploadRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'S3VMUploadRequest' from JSON`,
  );
}
