/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ScreenshotResponse = {
  /**
   * Base64-encoded JPEG image of the instance screenshot
   */
  image: string;
};

/** @internal */
export const ScreenshotResponse$inboundSchema: z.ZodType<
  ScreenshotResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  image: z.string(),
});

/** @internal */
export type ScreenshotResponse$Outbound = {
  image: string;
};

/** @internal */
export const ScreenshotResponse$outboundSchema: z.ZodType<
  ScreenshotResponse$Outbound,
  z.ZodTypeDef,
  ScreenshotResponse
> = z.object({
  image: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ScreenshotResponse$ {
  /** @deprecated use `ScreenshotResponse$inboundSchema` instead. */
  export const inboundSchema = ScreenshotResponse$inboundSchema;
  /** @deprecated use `ScreenshotResponse$outboundSchema` instead. */
  export const outboundSchema = ScreenshotResponse$outboundSchema;
  /** @deprecated use `ScreenshotResponse$Outbound` instead. */
  export type Outbound = ScreenshotResponse$Outbound;
}

export function screenshotResponseToJSON(
  screenshotResponse: ScreenshotResponse,
): string {
  return JSON.stringify(
    ScreenshotResponse$outboundSchema.parse(screenshotResponse),
  );
}

export function screenshotResponseFromJSON(
  jsonString: string,
): SafeParseResult<ScreenshotResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScreenshotResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScreenshotResponse' from JSON`,
  );
}
