/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ScrollRequest = {
  x: number;
  y: number;
  /**
   * Horizontal scroll amount
   */
  scrollX?: number | undefined;
  /**
   * Vertical scroll amount
   */
  scrollY?: number | undefined;
  /**
   * Optional step size for scroll movements. If not provided, movement will be continuous.
   */
  step?: number | null | undefined;
};

/** @internal */
export const ScrollRequest$inboundSchema: z.ZodType<
  ScrollRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  x: z.number().int(),
  y: z.number().int(),
  scroll_x: z.number().int().default(0),
  scroll_y: z.number().int().default(0),
  step: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    "scroll_x": "scrollX",
    "scroll_y": "scrollY",
  });
});

/** @internal */
export type ScrollRequest$Outbound = {
  x: number;
  y: number;
  scroll_x: number;
  scroll_y: number;
  step?: number | null | undefined;
};

/** @internal */
export const ScrollRequest$outboundSchema: z.ZodType<
  ScrollRequest$Outbound,
  z.ZodTypeDef,
  ScrollRequest
> = z.object({
  x: z.number().int(),
  y: z.number().int(),
  scrollX: z.number().int().default(0),
  scrollY: z.number().int().default(0),
  step: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    scrollX: "scroll_x",
    scrollY: "scroll_y",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ScrollRequest$ {
  /** @deprecated use `ScrollRequest$inboundSchema` instead. */
  export const inboundSchema = ScrollRequest$inboundSchema;
  /** @deprecated use `ScrollRequest$outboundSchema` instead. */
  export const outboundSchema = ScrollRequest$outboundSchema;
  /** @deprecated use `ScrollRequest$Outbound` instead. */
  export type Outbound = ScrollRequest$Outbound;
}

export function scrollRequestToJSON(scrollRequest: ScrollRequest): string {
  return JSON.stringify(ScrollRequest$outboundSchema.parse(scrollRequest));
}

export function scrollRequestFromJSON(
  jsonString: string,
): SafeParseResult<ScrollRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScrollRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScrollRequest' from JSON`,
  );
}
