/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type StandardResponse = {
  /**
   * Status of the operation
   */
  status: string;
  /**
   * Human-readable status message
   */
  message: string;
};

/** @internal */
export const StandardResponse$inboundSchema: z.ZodType<
  StandardResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string(),
  message: z.string(),
});

/** @internal */
export type StandardResponse$Outbound = {
  status: string;
  message: string;
};

/** @internal */
export const StandardResponse$outboundSchema: z.ZodType<
  StandardResponse$Outbound,
  z.ZodTypeDef,
  StandardResponse
> = z.object({
  status: z.string(),
  message: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StandardResponse$ {
  /** @deprecated use `StandardResponse$inboundSchema` instead. */
  export const inboundSchema = StandardResponse$inboundSchema;
  /** @deprecated use `StandardResponse$outboundSchema` instead. */
  export const outboundSchema = StandardResponse$outboundSchema;
  /** @deprecated use `StandardResponse$Outbound` instead. */
  export type Outbound = StandardResponse$Outbound;
}

export function standardResponseToJSON(
  standardResponse: StandardResponse,
): string {
  return JSON.stringify(
    StandardResponse$outboundSchema.parse(standardResponse),
  );
}

export function standardResponseFromJSON(
  jsonString: string,
): SafeParseResult<StandardResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StandardResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StandardResponse' from JSON`,
  );
}
