/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TypeRequest = {
  text: string;
  interval?: number | null | undefined;
};

/** @internal */
export const TypeRequest$inboundSchema: z.ZodType<
  TypeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  text: z.string(),
  interval: z.nullable(z.number()).optional(),
});

/** @internal */
export type TypeRequest$Outbound = {
  text: string;
  interval?: number | null | undefined;
};

/** @internal */
export const TypeRequest$outboundSchema: z.ZodType<
  TypeRequest$Outbound,
  z.ZodTypeDef,
  TypeRequest
> = z.object({
  text: z.string(),
  interval: z.nullable(z.number()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TypeRequest$ {
  /** @deprecated use `TypeRequest$inboundSchema` instead. */
  export const inboundSchema = TypeRequest$inboundSchema;
  /** @deprecated use `TypeRequest$outboundSchema` instead. */
  export const outboundSchema = TypeRequest$outboundSchema;
  /** @deprecated use `TypeRequest$Outbound` instead. */
  export type Outbound = TypeRequest$Outbound;
}

export function typeRequestToJSON(typeRequest: TypeRequest): string {
  return JSON.stringify(TypeRequest$outboundSchema.parse(typeRequest));
}

export function typeRequestFromJSON(
  jsonString: string,
): SafeParseResult<TypeRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TypeRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TypeRequest' from JSON`,
  );
}
